import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import initSqlJs from 'sql.js';
import {DomainEngine} from '../../src/domain/engine';import {proposalChange,toModelConstraints} from '../../src/components/merchant/model';
import type {DemoCommand} from '../../src/contracts/domain';import type {MerchantConstraints} from '../../src/contracts/assistant';
const SQL=await initSqlJs(),seed=new Uint8Array(fs.readFileSync('public/demo/seed.sqlite'));
function setup(){
 const e=new DomainEngine(new SQL.Database(seed),()=>Date.UTC(2026,8,21,3));let n=0;
 const snapshot=()=>e.snapshot(e.scope()),store=snapshot().conditions[0].storeId,skus=snapshot().conditions.filter(c=>c.storeId===store).slice(0,2).map(c=>c.sku);
 const role=(id:string)=>e.switchRole(id,e.scope()),merchant=()=>role('DEMO-MERCHANT-'+store);
 const send=(cmd:DemoCommand)=>e.dispatch(cmd,{...e.scope(),commandId:'cap-regression-'+(++n),correlationId:'cap-'+n});
 const condition=(sku:string,patch:Record<string,unknown>)=>{merchant();const c=e.condition(store,sku);send({type:'demo.updateCondition',storeId:store,sku,expectedConditionVersion:c.version,patch})};
 for(const sku of skus)condition(sku,{minimumOrderQty:1,orderMultiple:1,availableOrderQty:50,purchaseCostKrw:1000,supplyStatus:'available',observationStatus:'observed'});
 const request=(sku:string,q:number)=>{role('DEMO-CUSTOMER-001');const c=e.condition(store,sku);send({type:'request.create',sku,storeId:store,quantity:q,acceptedPriceKrw:c.sale_price_krw,conditionVersion:c.version,consent:{accepted:true,termsVersion:'v1'}})};
 const proposal=()=>snapshot().proposals.at(-1)!;
 const review=()=>{merchant();send({type:'merchant.review',storeId:store});return proposal()};
 const revise=(changes:Partial<MerchantConstraints>)=>{merchant();const p=proposal();send({type:'proposal.revise',proposalId:p.id,expectedProposalVersion:p.version,change:proposalChange(p,{budgetLimitKrw:null,excludeCategories:[],excludeProductIds:[],maxQuantity:null,restorePrevious:false,...changes})});return proposal()};
 const approve=()=>{const p=proposal();send({type:'proposal.approve',proposalId:p.id,expectedProposalVersion:p.version,confirmed:true});return snapshot().orders.at(-1)!};
 return {e,store,skus,snapshot,send,merchant,request,condition,proposal,review,revise,approve};
}
test('public SQLite deferred budget-zero request restores at explicit2, approval stores2 and original demand5 survives',()=>{const t=setup();try{const sku=t.skus[0];t.request(sku,5);t.review();assert.equal(t.revise({budgetLimitKrw:0}).deferred.length,1);const p=t.revise({budgetLimitKrw:50000,maxQuantity:2});assert.equal(p.constraints.maxQuantities?.[sku],2);assert.equal(p.lines[0].quantity,2);assert.equal(t.e.all('orders').length,0);assert.equal(t.approve().lines[0].orderedQty,2);assert.equal(t.snapshot().requests[0].quantity,5);assert.equal(t.e.demand(t.store)[0].newOrderNeedQty,3);t.e.assertInvariants()}finally{t.e.db.close()}});
test('mixed active/deferred bundle gets same explicit cap; budget-only preserves it and undo restores previous exact constraints',()=>{const t=setup();try{for(const sku of t.skus)t.request(sku,5);t.review();const before=t.revise({budgetLimitKrw:5000});assert.equal(before.lines.length,1);assert.equal(before.deferred.length,1);const p=t.revise({budgetLimitKrw:50000,maxQuantity:2});assert.equal(p.lines.length,2);assert(p.lines.every(l=>l.quantity===2));assert.deepEqual(p.constraints.maxQuantities,Object.fromEntries(t.skus.map(s=>[s,2])));const budget=t.revise({budgetLimitKrw:60000});assert.deepEqual(budget.constraints.maxQuantities,p.constraints.maxQuantities);t.send({type:'proposal.undo',proposalId:budget.id,expectedProposalVersion:budget.version});assert.deepEqual(t.proposal().constraints,p.constraints);const current=t.proposal();t.send({type:'proposal.undo',proposalId:current.id,expectedProposalVersion:current.version});assert.deepEqual(t.proposal().constraints,before.constraints);assert.equal(t.proposal().lines.length,1);assert.equal(t.e.all('orders').length,0)}finally{t.e.db.close()}});
test('configured10 above actual demand6 stays10 in future-copy constraints while real approval orders only6',()=>{const t=setup();try{const sku=t.skus[0];t.request(sku,6);t.review();let p=t.revise({maxQuantity:2});assert.equal(p.lines[0].quantity,2);p=t.revise({maxQuantity:10});assert.equal(p.lines[0].quantity,6);const copied=toModelConstraints(p)!;assert.equal(copied.maxQuantity,10);assert.equal(p.constraints.maxQuantities?.[sku],10);assert.equal(t.snapshot().policies.find(x=>x.storeId===t.store)!.maxQuantityPerReview,null);assert.equal(t.approve().lines[0].orderedQty,6);t.send({type:'policy.update',storeId:t.store,expectedPolicyVersion:t.e.policy(t.store).version,enabled:false,skuScope:[sku],categoryScope:[],dailyBudgetKrw:50000,maxQuantityPerReview:copied.maxQuantity,confirmed:true});assert.equal(t.snapshot().policies.find(x=>x.storeId===t.store)!.maxQuantityPerReview,10);assert.equal(t.e.all('orders').length,1)}finally{t.e.db.close()}});
test('adapter cap is bounded by MOQ/multiple, actual capacity and budget without excess demand',()=>{for(const [patch,budget,cap,expected]of [
 [{minimumOrderQty:6,orderMultiple:6},50000,3,0],
 [{minimumOrderQty:2,orderMultiple:2},50000,5,4],
 [{availableOrderQty:2},50000,8,2],
 [{availableOrderQty:7},1000,8,1],
] as [Record<string,number>,number,number,number][]){const t=setup();try{const sku=t.skus[0];t.condition(sku,patch);t.request(sku,10);t.review();t.revise({budgetLimitKrw:0});const p=t.revise({budgetLimitKrw:budget,maxQuantity:cap});assert.equal(p.constraints.maxQuantities?.[sku],cap);if(!expected){assert.equal(p.lines.length,0);assert.equal(p.deferred.length,1);assert.equal(t.e.all('orders').length,0)}else{assert.equal(p.lines[0].quantity,expected);assert.equal(t.approve().lines[0].orderedQty,expected)}assert.equal(t.snapshot().requests[0].quantity,10);t.e.assertInvariants()}finally{t.e.db.close()}}});
test('active policy smaller cap still constrains repaired current proposal; explicit approval is required',()=>{const t=setup();try{t.merchant();t.send({type:'policy.update',storeId:t.store,expectedPolicyVersion:t.e.policy(t.store).version,enabled:true,skuScope:[t.skus[1]],categoryScope:[],dailyBudgetKrw:50000,maxQuantityPerReview:2,confirmed:true});t.request(t.skus[0],10);t.review();const p=t.revise({maxQuantity:8});assert.equal(p.constraints.maxQuantities?.[t.skus[0]],8);assert.equal(p.lines[0].quantity,2);assert.equal(t.e.all('orders').length,0);assert.equal(t.approve().lines[0].orderedQty,2);assert.equal(t.e.all('orders').length,1)}finally{t.e.db.close()}});
