import type { Database, BindParams } from 'sql.js';
import type * as C from '../contracts/domain';
type Row = Record<string, any>;
const DAY=86400000;
export class DomainFailure extends Error { constructor(public code:string,message=code,public retryable=false){super(message)} }
function fail(code:string):never {throw new DomainFailure(code)}
function integer(n:unknown,min=0,max=Number.MAX_SAFE_INTEGER):number {if(typeof n!=='number'||!Number.isSafeInteger(n)||n<min||n>max)fail('INVALID_INPUT');return n}
function truth(v:unknown){if(v!==true)fail('CONSENT_REQUIRED')}
export function canonical(v:unknown):string {if(Array.isArray(v))return '['+v.map(canonical).join(',')+']';if(v&&typeof v==='object')return '{'+Object.entries(v).sort(([a],[b])=>a.localeCompare(b)).map(([k,x])=>JSON.stringify(k)+':'+canonical(x)).join(',')+'}';return JSON.stringify(v)}
const camel=(s:string)=>s.replace(/_([a-z])/g,(_,c)=>c.toUpperCase());
function dto(r:Row):Row {return Object.fromEntries(Object.entries(r).filter(([k])=>!['session_id','generation'].includes(k)).map(([k,v])=>k.endsWith('_json')?[camel(k.slice(0,-5)),JSON.parse(v)]:[camel(k),v]))}
export class DomainEngine {
  sessionId:string; generation=1; actorId='DEMO-CUSTOMER-001';roleEpoch=0; now=0; private commandId='';private ids:string[]=[]; private eventIds:string[]=[];
  constructor(public db:Database,private clock:()=>number=Date.now,sessionId='DEMO-SESSION-001'){this.sessionId=sessionId;db.run('PRAGMA foreign_keys=ON');this.initializeSession();}
  rows(sql:string,params:BindParams=[]):Row[]{const st=this.db.prepare(sql);try{st.bind(params);const out:Row[]=[];while(st.step())out.push(st.getAsObject());return out}finally{st.free()}}
  row(sql:string,params:BindParams=[]):Row|undefined{return this.rows(sql,params)[0]}
  run(sql:string,params:BindParams=[]){this.db.run(sql,params)}
  all(table:string,extra='',params:any[]=[]):Row[]{return this.rows(`SELECT * FROM ${table} WHERE session_id=? AND generation=? ${extra} ${/ORDER BY/i.test(extra)?"":"ORDER BY rowid"}`,[this.sessionId,this.generation,...params])}
  one(table:string,id:string):Row {return this.all(table,'AND id=?',[id])[0]??fail('NOT_FOUND')}
  insert(table:string,values:Row){const v={session_id:this.sessionId,generation:this.generation,...values};const k=Object.keys(v);this.run(`INSERT INTO ${table}(${k.join(',')}) VALUES(${k.map(()=>'?').join(',')})`,Object.values(v) as any[])}
  update(table:string,id:string,values:Row){const k=Object.keys(values);this.run(`UPDATE ${table} SET ${k.map(x=>x+'=?').join(',')} WHERE session_id=? AND generation=? AND id=?`,[...Object.values(values),this.sessionId,this.generation,id] as any[])}
  meta(key:string){const r=this.row('SELECT value FROM schema_meta WHERE key=?',[key]);return r?JSON.parse(r.value):null}
  id(prefix:string){return prefix+'-'+crypto.randomUUID()}
  session(){return this.row('SELECT * FROM sessions WHERE id=?',[this.sessionId])??fail('NOT_FOUND')}
  actor(){return this.one('actors',this.actorId)}
  time(){return integer(Math.trunc(this.clock()+this.session().clock_offset_ms))}
  scope():C.Scope{return {sessionId:this.sessionId,generation:this.generation,actorId:this.actorId,roleEpoch:this.roleEpoch}}
  check(scope:C.Scope){if(scope.sessionId!==this.sessionId||scope.generation!==this.generation)fail('STALE_GENERATION');if(scope.actorId!==this.actorId||scope.roleEpoch!==this.roleEpoch)fail('STALE_ROLE');this.actor()}
  merchant(store?:string){const a=this.actor();if(a.role!=='merchant'||(store&&a.store_id!==store))fail('FORBIDDEN');return a.store_id as string}
  customer(){if(this.actor().role!=='customer')fail('FORBIDDEN')}
  ownedRequest(id:string){const r=this.one('purchase_requests',id);this.customer();if(r.actor_id!==this.actorId)fail('FORBIDDEN');return r}
  initializeSession(){let s=this.row('SELECT * FROM sessions WHERE id=?',[this.sessionId]);if(!s){this.run('INSERT INTO sessions VALUES(?,1,0,1,0,?)',[this.sessionId,this.clock()]);s=this.session();this.generation=s.generation;this.seedMutable()}else this.generation=s.generation;}
  seedMutable(){const n=this.meta('customerCount')??30;for(let i=1;i<=n;i++)this.insert('actors',{id:`DEMO-CUSTOMER-${String(i).padStart(3,'0')}`,role:'customer',display_name:`시연 고객 ${i}`,store_id:null});const stores=this.rows('SELECT * FROM stores ORDER BY id'),products=this.rows('SELECT * FROM products ORDER BY sku');stores.forEach((s,si)=>{this.insert('actors',{id:'DEMO-MERCHANT-'+s.id,role:'merchant',display_name:s.name+' 시연 경영주',store_id:s.id});this.insert('policies',{id:'POLICY-'+s.id,store_id:s.id,enabled:0,sku_scope_json:'[]',category_scope_json:'[]',daily_budget_krw:this.meta('defaultBudgetKrw')??100000,max_quantity_per_review:null,version:1,approved_by:null,approved_at:null});products.forEach((p,pi)=>{if(pi<3||(pi+si)%4===0)this.insert('conditions',{store_id:s.id,sku:p.sku,version:1,sale_price_krw:1500+pi%20*100,purchase_cost_krw:1000+pi%20*70,minimum_order_qty:1,order_multiple:1,available_order_qty:60,assortment_status:'listed',stock_qty:pi%4,observation_status:'observed',observed_at:this.clock(),supply_status:'available',reason:null,orderable_until:null})})})}
  condition(store:string,sku:string){return this.all('conditions','AND store_id=? AND sku=?',[store,sku])[0]??fail('NOT_FOUND')}
  policy(store:string){return this.all('policies','AND store_id=?',[store])[0]??fail('NOT_FOUND')}
  sequence(){const n=this.session().next_sequence;this.run('UPDATE sessions SET next_sequence=next_sequence+1 WHERE id=?',[this.sessionId]);return n}
  consent(r:Row){return this.all('consent_revisions','AND request_id=? AND version=?',[r.id,r.consent_version])[0]??fail('INVARIANT_VIOLATION')}
  consentStatus(r:Row):C.ConsentView['status']{if(r.status==='cancelled')return 'cancelled';if(this.all('allocation_sources',"AND request_id=? AND status='paid'",[r.id]).length)return 'not_applicable_paid';const c=this.consent(r);if(this.now>=c.expires_at)return 'expired';const cond=this.condition(r.store_id,r.sku);if(c.sku!==r.sku||c.store_id!==r.store_id||c.quantity!==r.quantity||c.unit_price_krw!==cond.sale_price_krw)return 'mismatch';return 'valid'}
  event(type:string,entity:string|null=null){const id=this.id('EV');this.insert('events',{id,command_id:this.commandId,type,entity_id:entity,created_at:this.now});this.eventIds.push(id)}
  notify(actor:string,key:string,type:string,body:string){if(!this.all('notifications','AND actor_id=? AND event_key=? AND type=?',[actor,key,type]).length)this.insert('notifications',{id:this.id('NOTICE'),actor_id:actor,event_key:key,type,body,created_at:this.now,read_at:null})}
  setConsent(r:Row,terms:string,keepTimes=false){if(typeof terms!=='string'||!terms.trim()||terms.length>80)fail('CONSENT_REQUIRED');const old=r.consent_version?this.consent(r):null;const version=r.consent_version+1;this.insert('consent_revisions',{request_id:r.id,version,terms_version:terms,sku:r.sku,store_id:r.store_id,quantity:r.quantity,unit_price_krw:r.accepted_price_krw,consent_at:keepTimes?old!.consent_at:this.now,expires_at:keepTimes?old!.expires_at:this.now+7*DAY});this.update('purchase_requests',r.id,{consent_version:version});}
  create(input:C.CreateRequest){this.customer();truth(input.consent?.accepted);integer(input.quantity,1,20);if(!input.consent.termsVersion)fail('CONSENT_REQUIRED');const c=this.condition(input.storeId,input.sku);if(c.version!==input.conditionVersion)fail('VERSION_CONFLICT');if(c.sale_price_krw!==input.acceptedPriceKrw)fail('CONSENT_MISMATCH');if(c.observation_status!=='observed')fail('CONDITION_UNAVAILABLE');if(this.all('purchase_requests','AND actor_id=? AND store_id=? AND sku=? AND is_active=1',[this.actorId,input.storeId,input.sku]).length)fail('ACTIVE_REQUEST_EXISTS');if(input.sourceNeedId){const need=this.one('need_records',input.sourceNeedId);if(need.actor_id!==this.actorId)fail('FORBIDDEN')}
    const id=this.id('REQ');const r={id,actor_id:this.actorId,store_id:input.storeId,sku:input.sku,quantity:input.quantity,accepted_price_krw:input.acceptedPriceKrw,sequence:this.sequence(),status:'pending',is_active:1,pending_reason:null,consent_version:0,payment_cycle:1,version:1,created_at:this.now,updated_at:this.now};this.insert('purchase_requests',r);this.setConsent(r,input.consent.termsVersion);if(input.sourceNeedId)this.run('UPDATE recommendation_events SET followup_request_id=? WHERE session_id=? AND generation=? AND need_id=? AND candidate_sku=?',[id,this.sessionId,this.generation,input.sourceNeedId,input.sku]);this.ids.push(id);this.event('request.created',id);return id;
  }
  release(r:Row,reason:string){this.run("UPDATE allocation_sources SET status='released' WHERE session_id=? AND generation=? AND request_id=? AND status='held'",[this.sessionId,this.generation,r.id]);this.run('UPDATE request_order_links SET active=0,released_reason=? WHERE session_id=? AND generation=? AND request_id=? AND active=1',[reason,this.sessionId,this.generation,r.id]);this.update('purchase_requests',r.id,{status:'review_required',pending_reason:reason,version:r.version+1,updated_at:this.now});}
  cancel(r:Row){if(this.consentStatus(r)==='not_applicable_paid')fail('CANCELLATION_NOT_ALLOWED');this.release(r,'cancelled');this.update('purchase_requests',r.id,{status:'cancelled',is_active:0});this.event('request.cancelled',r.id)}
  line(id:string):Row {const l=this.one('order_lines',id);return {...l,store_id:this.one('orders',l.order_id).store_id}}
  pools(store?:string,sku?:string):C.PoolView[]{return this.all('order_lines','AND confirmed_qty IS NOT NULL ORDER BY supply_confirmed_at,id').map(l=>{const o=this.one('orders',l.order_id);const a=this.all('allocation_sources',"AND line_id=? AND status!='released'",[l.id]);const held=a.filter(x=>x.status==='held').reduce((n,x)=>n+x.quantity,0),paid=a.filter(x=>x.status==='paid').reduce((n,x)=>n+x.quantity,0);return {sourceLineId:l.id,storeId:o.store_id,sku:l.sku,salePriceKrw:l.sale_price_krw,confirmedQty:l.confirmed_qty,unallocatedQty:l.confirmed_qty-held-paid,heldQty:held,paidQty:paid,receivedAt:l.received_at}}).filter(p=>(!store||p.storeId===store)&&(!sku||p.sku===sku))}
  demand(store:string):C.DemandRow[]{const rs=this.all('purchase_requests','AND store_id=?',[store]);return [...new Set(rs.map(r=>r.sku))].sort().map(sku=>{const rr=rs.filter(r=>r.sku===sku);const cond=this.condition(store,sku);const pending=rr.filter(r=>r.status==='pending'&&this.consentStatus(r)==='valid').reduce((n,r)=>n+r.quantity,0);const lines=this.all('order_lines','AND sku=? AND confirmed_qty IS NULL',[sku]).filter(l=>this.one('orders',l.order_id).store_id===store&&l.sale_price_krw===cond.sale_price_krw);const pool=this.pools(store,sku).filter(p=>p.salePriceKrw===cond.sale_price_krw);const coverage=lines.reduce((n,l)=>n+l.ordered_qty,0),unallocated=pool.reduce((n,p)=>n+p.unallocatedQty,0);const active=rr.reduce((n,r)=>n+this.all('request_order_links','AND request_id=? AND active=1',[r.id]).reduce((m,l)=>m+l.quantity,0),0);return {sku,storeId:store,requestedQty:rr.filter(r=>r.is_active).reduce((n,r)=>n+r.quantity,0),validPendingQty:pending,activeLinkedQty:active,pendingOrderCoverageQty:coverage,unallocatedPoolQty:unallocated,newOrderNeedQty:Math.max(0,pending-coverage-unallocated),allocatedHeldQty:pool.reduce((n,p)=>n+p.heldQty,0),paidQty:pool.reduce((n,p)=>n+p.paidQty,0),deferredReasons:[...new Set(rr.map(r=>r.pending_reason).filter(Boolean))],customerDetailAvailable:true}})}
  day(){return new Date(this.now+9*3600000).toISOString().slice(0,10)}
  budget(store:string,day=this.day()):C.BudgetView{const ls=this.all('budget_ledger','AND store_id=? AND budget_day=?',[store,day]);const reserved=ls.reduce((n,l)=>n+l.reserved_krw,0),secured=ls.reduce((n,l)=>n+l.secured_krw,0);return {storeId:store,budgetDay:day,reservedKrw:reserved,securedKrw:secured,usedKrw:reserved+secured,limitKrw:this.policy(store).daily_budget_krw}}
  fingerprint(store:string){return canonical({demand:this.demand(store),conditions:this.all('conditions','AND store_id=? ORDER BY sku',[store]),policy:this.policy(store),budget:this.budget(store)})}
  propose(store:string,change:C.ProposalChange={scope:'once'},auto=false){const p=this.policy(store);const budget=this.budget(store);let left=Math.min(budget.limitKrw-budget.usedKrw,change.budgetCapKrw??Number.MAX_SAFE_INTEGER);const lines:C.ProposalLine[]=[],deferred:C.ProposalView['deferred']=[];
    for(const d of this.demand(store)){if(!d.newOrderNeedQty)continue;const c=this.condition(store,d.sku);const product=this.row('SELECT * FROM products WHERE sku=?',[d.sku])!;let reason='';if(change.excludeSkus?.includes(d.sku)||change.excludeCategories?.includes(product.category))reason='excluded';if(auto){const ss=JSON.parse(p.sku_scope_json),cs=JSON.parse(p.category_scope_json);if((ss.length||cs.length)&&!ss.includes(d.sku)&&!cs.includes(product.category))reason='outside_policy'}if(c.supply_status!=='available'||c.observation_status!=='observed'||(c.orderable_until!==null&&this.now>=c.orderable_until))reason='supply_unavailable';const q=Math.floor(Math.min(d.newOrderNeedQty,c.available_order_qty,Math.floor(left/c.purchase_cost_krw),change.maxQuantities?.[d.sku]??Number.MAX_SAFE_INTEGER,p.enabled?(p.max_quantity_per_review??Number.MAX_SAFE_INTEGER):Number.MAX_SAFE_INTEGER)/c.order_multiple)*c.order_multiple;if(!reason&&q<c.minimum_order_qty)reason=c.available_order_qty===0?'capacity_exhausted':left<c.purchase_cost_krw?'budget_insufficient':'below_minimum';if(reason){deferred.push({sku:d.sku,reason,nextAction:'조건을 확인한 뒤 다시 검토해 주세요.'});continue}const total=q*c.purchase_cost_krw;integer(total);left-=total;lines.push({sku:d.sku,quantity:q,purchaseCostKrw:c.purchase_cost_krw,salePriceKrw:c.sale_price_krw,conditionVersion:c.version,totalKrw:total})}
    return {lines,deferred,totalKrw:lines.reduce((n,l)=>n+l.totalKrw,0),sourceFingerprint:this.fingerprint(store)};
  }
  saveProposal(store:string,change:C.ProposalChange={scope:'once'}){const calculated=this.propose(store,change);const previous=this.all('proposals',"AND store_id=? AND status='draft'",[store]).find(p=>p.source_fingerprint===calculated.sourceFingerprint&&canonical(JSON.parse(p.constraints_json))===canonical(change));if(previous)return previous.id;const id=this.id('PROP');this.insert('proposals',{id,store_id:store,version:1,status:'draft',source_fingerprint:calculated.sourceFingerprint,constraints_json:JSON.stringify(change),lines_json:JSON.stringify(calculated.lines),deferred_json:JSON.stringify(calculated.deferred),total_krw:calculated.totalKrw,history_json:'[]',order_id:null});this.ids.push(id);return id}
  approve(store:string,lines:C.ProposalLine[],type:'manual'|'policy'){if(!lines.length)return null;const policy=this.policy(store),orderId=this.id('ORDER');const total=lines.reduce((n,l)=>n+l.totalKrw,0);if(total+this.budget(store).usedKrw>policy.daily_budget_krw)fail('BUDGET_EXCEEDED');this.insert('orders',{id:orderId,store_id:store,approval_type:type,policy_version:policy.version,budget_day:this.day(),created_at:this.now});
    for(const l of lines){const c=this.condition(store,l.sku),d=this.demand(store).find(d=>d.sku===l.sku)!;if(c.version!==l.conditionVersion||l.quantity>c.available_order_qty||l.quantity>d.newOrderNeedQty)fail('STALE_PROPOSAL');const lineId=this.id('LINE');this.insert('order_lines',{id:lineId,order_id:orderId,sku:l.sku,ordered_qty:l.quantity,confirmed_qty:null,received_qty:null,sale_price_krw:l.salePriceKrw,purchase_cost_krw:l.purchaseCostKrw,condition_version:c.version,supply_confirmed_at:null,received_at:null});this.run('UPDATE conditions SET available_order_qty=available_order_qty-?,version=version+1 WHERE session_id=? AND generation=? AND store_id=? AND sku=?',[l.quantity,this.sessionId,this.generation,store,l.sku]);this.insert('budget_ledger',{line_id:lineId,store_id:store,budget_day:this.day(),reserved_krw:l.totalKrw,secured_krw:0,settled:0});let remaining=l.quantity;for(const r of this.all('purchase_requests',"AND store_id=? AND sku=? AND status='pending' ORDER BY sequence",[store,l.sku])){if(this.consentStatus(r)!=='valid')continue;const linked=this.all('request_order_links','AND request_id=? AND active=1',[r.id]).reduce((n,x)=>n+x.quantity,0);const q=Math.min(remaining,Math.max(0,r.quantity-linked));if(q){this.insert('request_order_links',{id:this.id('LINK'),request_id:r.id,line_id:lineId,quantity:q,active:1,released_reason:null});remaining-=q}if(!remaining)break}this.ids.push(lineId)}this.ids.push(orderId);this.event('order.submitted',orderId);return orderId;
  }
  auto(store:string){const p=this.policy(store);if(p.enabled&&p.approved_by){const x=this.propose(store,{scope:'once'},true);this.approve(store,x.lines,'policy')}}
  payment(r:Row){const attempts=this.all('mock_payments','AND request_id=? AND cycle=?',[r.id,r.payment_cycle]);if(attempts.length>=2)fail('PAYMENT_RETRY_NOT_ALLOWED');let outcomes=this.all('demo_payment_outcomes','AND actor_id=?',[r.actor_id])[0];let outcome='success';if(outcomes){const list=JSON.parse(outcomes.outcomes_json);outcome=list.shift()??'success';this.run('UPDATE demo_payment_outcomes SET outcomes_json=? WHERE session_id=? AND generation=? AND actor_id=?',[JSON.stringify(list),this.sessionId,this.generation,r.actor_id])}const reservation=this.all('reservations','AND request_id=? AND cycle=?',[r.id,r.payment_cycle])[0];const amount=integer(r.quantity*r.accepted_price_krw);this.insert('mock_payments',{id:this.id('PAY'),request_id:r.id,cycle:r.payment_cycle,attempt:attempts.length+1,status:outcome==='success'?'succeeded':'failed',amount_krw:amount,created_at:this.now});const id=reservation?.id??this.id('RES');if(!reservation)this.insert('reservations',{id,request_id:r.id,cycle:r.payment_cycle,code:id,quantity:r.quantity,total_krw:amount,status:'payment_pending',hold_expires_at:null,pickup_available_at:null,pickup_deadline_at:null,collected_at:null});if(outcome==='success'){this.run("UPDATE allocation_sources SET status='paid' WHERE session_id=? AND generation=? AND request_id=? AND cycle=? AND status='held'",[this.sessionId,this.generation,r.id,r.payment_cycle]);this.update('reservations',id,{status:'confirmed',hold_expires_at:null});this.update('purchase_requests',r.id,{status:'reserved',pending_reason:null});this.notify(r.actor_id,id,'reservation_confirmed','모의 결제가 완료되어 예약이 확정됐습니다.');this.pickupReady(this.one('purchase_requests',r.id));}else{this.update('reservations',id,{status:'payment_failed',hold_expires_at:reservation?.hold_expires_at??this.now+600000});if(attempts.length===1)this.release(r,'payment_attempts_exhausted');else this.update('purchase_requests',r.id,{status:'allocated',pending_reason:'payment_failed'})}this.event('payment.'+outcome,r.id)}
  pickupReady(r:Row){const rv=this.all('reservations','AND request_id=? AND cycle=?',[r.id,r.payment_cycle])[0];if(!rv||rv.status!=='confirmed'||rv.pickup_available_at!==null)return;const sources=this.all('allocation_sources',"AND request_id=? AND cycle=? AND status='paid'",[r.id,r.payment_cycle]);if(sources.length&&sources.every(a=>this.one('order_lines',a.line_id).received_at!==null)){this.update('reservations',rv.id,{status:'pickup_ready',pickup_available_at:this.now,pickup_deadline_at:this.now+2*DAY});this.notify(r.actor_id,rv.id,'pickup_ready','입고됐습니다. 알림 생성 시각부터 48시간 안에 수령해 주세요.');this.event('reservation.pickup_ready',rv.id)}}
  allocate(store:string,sku:string){for(const r of this.all('purchase_requests',"AND store_id=? AND sku=? AND status='pending' ORDER BY sequence",[store,sku])){if(this.consentStatus(r)!=='valid')continue;const pools=this.pools(store,sku).filter(p=>p.salePriceKrw===r.accepted_price_krw&&p.unallocatedQty>0);if(pools.reduce((n,p)=>n+p.unallocatedQty,0)<r.quantity)break;let remaining=r.quantity;for(const p of pools){const q=Math.min(remaining,p.unallocatedQty);this.insert('allocation_sources',{id:this.id('ALLOC'),request_id:r.id,cycle:r.payment_cycle,line_id:p.sourceLineId,quantity:q,status:'held'});remaining-=q;if(!remaining)break}this.run("UPDATE request_order_links SET active=0,released_reason='allocated' WHERE session_id=? AND generation=? AND request_id=? AND active=1",[this.sessionId,this.generation,r.id]);this.update('purchase_requests',r.id,{status:'allocated',pending_reason:null});this.payment(this.one('purchase_requests',r.id))}}
  sweep(){for(const r of this.all('purchase_requests',"AND status IN('pending','allocated')")){if(this.condition(r.store_id,r.sku).supply_status==='discontinued'){this.release(r,'supply_discontinued');continue}const status=this.consentStatus(r);if(status==='expired'||status==='mismatch'){this.release(r,'consent_'+status);continue}const rv=this.all('reservations','AND request_id=? AND cycle=?',[r.id,r.payment_cycle])[0];if(rv?.status==='payment_failed'&&rv.hold_expires_at!==null&&this.now>=rv.hold_expires_at)this.release(r,'payment_hold_expired')}
    for(const rv of this.all('reservations',"AND status='pickup_ready' AND pickup_deadline_at<=?",[this.now])){this.update('reservations',rv.id,{status:'pickup_expired'});this.update('purchase_requests',rv.request_id,{is_active:0});this.event('reservation.pickup_expired',rv.id)}
  }
  reconcile(autoStores?:string[]){this.sweep();const allowed=autoStores===undefined?new Set(this.rows('SELECT id FROM stores').map(s=>s.id)):new Set(autoStores);for(const s of this.rows('SELECT id FROM stores')){for(const d of this.demand(s.id))this.allocate(s.id,d.sku);if(allowed.has(s.id))this.auto(s.id)}}
  automaticStores(cmd:C.DemoCommand):string[]{switch(cmd.type){case 'request.create':return [cmd.storeId];case 'request.replace':return [cmd.newRequest.storeId];case 'request.changeQuantity':case 'request.reconsent':return [this.one('purchase_requests',cmd.requestId).store_id];case 'policy.update':case 'demo.updateCondition':case 'autoOrder.run':return [cmd.storeId];case 'demo.reconcile':return [this.merchant()];default:return []}}

  validateProposalChange(value: unknown): asserts value is C.ProposalChange {
    if (!value || typeof value !== 'object' || Array.isArray(value)) fail('INVALID_INPUT');
    const change = value as Record<string, unknown>;
    const allowed = new Set(['scope', 'excludeSkus', 'excludeCategories', 'budgetCapKrw', 'maxQuantities']);
    if (Object.keys(change).some(key => !allowed.has(key)) || change.scope !== 'once') fail('INVALID_INPUT');
    for (const key of ['excludeSkus', 'excludeCategories'] as const) {
      const values = change[key];
      if (values === undefined) continue;
      if (!Array.isArray(values) || values.some(value => typeof value !== 'string')) fail('INVALID_INPUT');
      for (const value of values) {
        const column = key === 'excludeSkus' ? 'sku' : 'category';
        if (!this.row(`SELECT sku FROM products WHERE ${column}=? LIMIT 1`, [value])) fail('INVALID_INPUT');
      }
    }
    if (change.budgetCapKrw !== undefined) integer(change.budgetCapKrw);
    if (change.maxQuantities !== undefined) {
      if (!change.maxQuantities || typeof change.maxQuantities !== 'object' || Array.isArray(change.maxQuantities)) fail('INVALID_INPUT');
      for (const [sku, quantity] of Object.entries(change.maxQuantities)) {
        if (!this.row('SELECT sku FROM products WHERE sku=?', [sku])) fail('INVALID_INPUT');
        integer(quantity);
      }
    }
  }
  execute(cmd:C.DemoCommand){
    switch(cmd.type){
      case 'request.create':this.create(cmd);break;
      case 'request.changeQuantity':case 'request.reconsent':{const r=this.ownedRequest(cmd.requestId);if(r.version!==cmd.expectedRequestVersion)fail('VERSION_CONFLICT');truth(cmd.consent?.accepted);integer(cmd.quantity,1,20);if(this.consentStatus(r)==='not_applicable_paid'||r.status==='cancelled')fail('CANCELLATION_NOT_ALLOWED');if(cmd.type==='request.changeQuantity'&&(r.status!=='pending'||this.all('request_order_links','AND request_id=? AND active=1',[r.id]).length))fail('REQUEST_LINKED');const condition=this.condition(r.store_id,r.sku);if(condition.sale_price_krw!==cmd.acceptedPriceKrw)fail('CONSENT_MISMATCH');if(cmd.type==='request.reconsent'&&condition.version!==cmd.conditionVersion)fail('VERSION_CONFLICT');const keep=cmd.type==='request.changeQuantity'&&cmd.quantity<r.quantity&&this.consentStatus(r)==='valid';this.release(r,'reconsent');const changed={...r,quantity:cmd.quantity,accepted_price_krw:cmd.acceptedPriceKrw};this.update('purchase_requests',r.id,{quantity:cmd.quantity,accepted_price_krw:cmd.acceptedPriceKrw,status:'pending',pending_reason:null,sequence:keep?r.sequence:this.sequence(),payment_cycle:r.payment_cycle+1,version:r.version+1});this.setConsent(changed,cmd.consent.termsVersion,keep);this.ids.push(r.id);break}
      case 'request.cancel':{const r=this.ownedRequest(cmd.requestId);if(r.version!==cmd.expectedRequestVersion)fail('VERSION_CONFLICT');this.cancel(r);break}
      case 'request.replace':{const r=this.ownedRequest(cmd.originalRequestId);if(r.version!==cmd.expectedRequestVersion)fail('VERSION_CONFLICT');this.cancel(r);this.create(cmd.newRequest);break}
      case 'need.record':{this.customer();if(!cmd.originalText.trim()||cmd.originalText.length>2000||(['error','lookup_error','network_error','timeout','system_error'].includes(cmd.reason)||['error','lookup_error','network_error','timeout','system_error'].includes(cmd.identificationStatus)))fail('INVALID_INPUT');if(!this.row('SELECT id FROM stores WHERE id=?',[cmd.storeId]))fail('NOT_FOUND');for(const sku of cmd.candidateSkus)if(!this.row('SELECT sku FROM products WHERE sku=?',[sku]))fail('INVALID_INPUT');const id=this.id('NEED');this.insert('need_records',{id,actor_id:this.actorId,store_id:cmd.storeId,original_text:cmd.originalText,dialogue_json:JSON.stringify(cmd.dialogue),extracted_clues_json:JSON.stringify(cmd.extractedClues),candidate_skus_json:JSON.stringify(cmd.candidateSkus),identification_status:cmd.identificationStatus,reason:cmd.reason,observed_at:integer(cmd.observedAt),source_refs_json:JSON.stringify(cmd.sourceRefs),created_at:this.now});this.ids.push(id);break}
      case 'recommendation.record':{const need=this.one('need_records',cmd.needId);this.customer();if(need.actor_id!==this.actorId)fail('FORBIDDEN');this.insert('recommendation_events',{id:this.id('REC'),need_id:need.id,candidate_sku:cmd.candidateSku,kind:cmd.kind,action:cmd.action,followup_request_id:null});break}
      case 'merchant.review':this.merchant(cmd.storeId);this.reconcile([cmd.storeId]);this.ids.push(this.saveProposal(cmd.storeId));break;
      case 'proposal.revise':case 'proposal.undo':{const p=this.one('proposals',cmd.proposalId);this.merchant(p.store_id);if(p.version!==cmd.expectedProposalVersion||p.status!=='draft')fail('STALE_PROPOSAL');const history=JSON.parse(p.history_json);let change:C.ProposalChange;if(cmd.type==='proposal.undo'){if(!history.length)fail('INVALID_INPUT');change=history.pop()}else{change=cmd.change;this.validateProposalChange(change);history.push(JSON.parse(p.constraints_json));}const next=this.propose(p.store_id,change);this.update('proposals',p.id,{version:p.version+1,constraints_json:JSON.stringify(change),history_json:JSON.stringify(history),source_fingerprint:next.sourceFingerprint,lines_json:JSON.stringify(next.lines),deferred_json:JSON.stringify(next.deferred),total_krw:next.totalKrw});this.ids.push(p.id);break}
      case 'proposal.approve':{truth(cmd.confirmed);const p=this.one('proposals',cmd.proposalId);this.merchant(p.store_id);if(p.status!=='draft'||p.version!==cmd.expectedProposalVersion||p.source_fingerprint!==this.fingerprint(p.store_id))fail('STALE_PROPOSAL');const orderId=this.approve(p.store_id,JSON.parse(p.lines_json),'manual');if(!orderId)fail('NO_EXECUTABLE_LINES');this.update('proposals',p.id,{status:'approved',order_id:orderId});break}
      case 'policy.update':{this.merchant(cmd.storeId);truth(cmd.confirmed);const allowed=new Set(['type','storeId','expectedPolicyVersion','enabled','skuScope','categoryScope','dailyBudgetKrw','maxQuantityPerReview','confirmed']);if(Object.keys(cmd).some(k=>!allowed.has(k)))fail('INVALID_INPUT');if(cmd.maxQuantityPerReview!==undefined&&cmd.maxQuantityPerReview!==null)integer(cmd.maxQuantityPerReview,1);if(!Array.isArray(cmd.skuScope)||!Array.isArray(cmd.categoryScope))fail('INVALID_INPUT');for(const category of cmd.categoryScope)if(!this.row('SELECT sku FROM products WHERE category=? LIMIT 1',[category]))fail('INVALID_INPUT');const p=this.policy(cmd.storeId);if(p.version!==cmd.expectedPolicyVersion)fail('VERSION_CONFLICT');integer(cmd.dailyBudgetKrw);if(cmd.dailyBudgetKrw<this.budget(cmd.storeId).usedKrw)fail('BUDGET_EXCEEDED');for(const sku of cmd.skuScope)if(!this.row('SELECT sku FROM products WHERE sku=?',[sku]))fail('INVALID_INPUT');if(typeof cmd.enabled!=='boolean')fail('INVALID_INPUT');this.update('policies',p.id,{enabled:Number(cmd.enabled),sku_scope_json:JSON.stringify(cmd.skuScope),category_scope_json:JSON.stringify(cmd.categoryScope),daily_budget_krw:cmd.dailyBudgetKrw,max_quantity_per_review:cmd.maxQuantityPerReview===undefined?(p.max_quantity_per_review??null):cmd.maxQuantityPerReview,version:p.version+1,approved_by:this.actorId,approved_at:this.now});break}
      case 'autoOrder.run':this.merchant(cmd.storeId);break;
      case 'demo.confirmSupply':{const l=this.line(cmd.lineId);this.merchant(l.store_id);integer(cmd.confirmedQty,0,l.ordered_qty);if(l.confirmed_qty!==null)fail('SUPPLY_ALREADY_CONFIRMED');this.update('order_lines',l.id,{confirmed_qty:cmd.confirmedQty,supply_confirmed_at:this.now});this.run("UPDATE request_order_links SET active=0,released_reason='supply_final' WHERE session_id=? AND generation=? AND line_id=?",[this.sessionId,this.generation,l.id]);this.run('UPDATE budget_ledger SET reserved_krw=0,secured_krw=?,settled=1 WHERE session_id=? AND generation=? AND line_id=? AND settled=0',[cmd.confirmedQty*l.purchase_cost_krw,this.sessionId,this.generation,l.id]);this.event('supply.confirmed',l.id);break}
      case 'demo.receive':{const l=this.line(cmd.lineId);this.merchant(l.store_id);if(l.confirmed_qty===null)fail('INVALID_INPUT');if(l.received_at!==null)fail('RECEIPT_ALREADY_RECORDED');if(cmd.receivedQty!==l.confirmed_qty)fail('INVALID_INPUT');this.update('order_lines',l.id,{received_qty:cmd.receivedQty,received_at:this.now});for(const a of this.all('allocation_sources',"AND line_id=? AND status='paid'",[l.id]))this.pickupReady(this.one('purchase_requests',a.request_id));this.event('supply.received',l.id);break}
      case 'payment.retry':{const r=this.ownedRequest(cmd.requestId);const rv=this.all('reservations','AND request_id=? AND cycle=?',[r.id,r.payment_cycle])[0];if(r.payment_cycle!==cmd.paymentCycle||r.status!=='allocated'||rv?.status!=='payment_failed'||this.now>=rv.hold_expires_at||this.consentStatus(r)!=='valid')fail('PAYMENT_RETRY_NOT_ALLOWED');this.payment(r);break}
      case 'merchant.collect':{const store=this.merchant();const rv=this.all('reservations','AND code=?',[cmd.reservationCode])[0]??fail('NOT_FOUND');const r=this.one('purchase_requests',rv.request_id);if(r.store_id!==store)fail('FORBIDDEN');if(rv.status==='collected')fail('ALREADY_COLLECTED');if(rv.pickup_deadline_at!==null&&this.now>=rv.pickup_deadline_at)fail('PICKUP_EXPIRED');if(rv.status!=='pickup_ready')fail('PICKUP_NOT_READY');this.update('reservations',rv.id,{status:'collected',collected_at:this.now});this.update('purchase_requests',r.id,{is_active:0});this.event('reservation.collected',rv.id);break}
      case 'notification.read':{const n=this.one('notifications',cmd.notificationId);if(n.actor_id!==this.actorId)fail('FORBIDDEN');if(n.read_at===null)this.update('notifications',n.id,{read_at:this.now});break}
      case 'demo.updateCondition':{this.merchant(cmd.storeId);const c=this.condition(cmd.storeId,cmd.sku);if(c.version!==cmd.expectedConditionVersion)fail('VERSION_CONFLICT');const fields:Record<string,string>={salePriceKrw:'sale_price_krw',purchaseCostKrw:'purchase_cost_krw',minimumOrderQty:'minimum_order_qty',orderMultiple:'order_multiple',availableOrderQty:'available_order_qty',assortmentStatus:'assortment_status',stockQty:'stock_qty',observationStatus:'observation_status',observedAt:'observed_at',supplyStatus:'supply_status',reason:'reason',orderableUntil:'orderable_until'};const out:Row={};for(const [k,v]of Object.entries(cmd.patch)){if(!fields[k])fail('INVALID_INPUT');out[fields[k]]=v}for(const k of ['sale_price_krw','available_order_qty'])if(k in out)integer(out[k]);for(const k of ['purchase_cost_krw','minimum_order_qty','order_multiple'])if(k in out)integer(out[k],1);if(out.stock_qty!==undefined&&out.stock_qty!==null)integer(out.stock_qty);for(const [k,allowed]of Object.entries({assortment_status:['listed','not_listed','unknown'],observation_status:['observed','error','unknown'],supply_status:['available','restricted','discontinued','unknown']}))if(k in out&&!allowed.includes(out[k]))fail('INVALID_INPUT');out.version=c.version+1;this.run(`UPDATE conditions SET ${Object.keys(out).map(k=>k+'=?').join(',')} WHERE session_id=? AND generation=? AND store_id=? AND sku=?`,[...Object.values(out),this.sessionId,this.generation,cmd.storeId,cmd.sku]);break}
      case 'demo.setPaymentOutcome':this.merchant();{const target=this.one('actors',cmd.actorId);if(target.role!=='customer'||!cmd.outcomes.every(o=>o==='success'||o==='failure')||cmd.outcomes.length>20)fail('INVALID_INPUT');this.run('INSERT OR REPLACE INTO demo_payment_outcomes VALUES(?,?,?,?)',[this.sessionId,this.generation,cmd.actorId,JSON.stringify(cmd.outcomes)]);break}
      case 'demo.advanceTime':this.merchant();integer(cmd.deltaMs,1,30*DAY);this.run('UPDATE sessions SET clock_offset_ms=clock_offset_ms+? WHERE id=?',[cmd.deltaMs,this.sessionId]);this.now+=cmd.deltaMs;break;
      case 'demo.reconcile':this.merchant();break;
      case 'demo.reset':{this.merchant();truth(cmd.confirmed);this.run('UPDATE sessions SET generation=generation+1,revision=0,next_sequence=1,clock_offset_ms=0 WHERE id=?',[this.sessionId]);this.generation++;this.seedMutable();this.now=this.time();break}
      case 'agent.record':{if(!['live','fixture'].includes(cmd.mode)||!['ok','lookup_error'].includes(cmd.status))fail('INVALID_INPUT');if(cmd.catalogHash!==this.meta('catalogHash'))fail('VERSION_CONFLICT');integer(cmd.latencyMs);if(typeof cmd.providerCalled!=='boolean')fail('INVALID_INPUT');const allowed=new Set(['type','requestId','mode','model','promptVersion','catalogHash','usage','providerCalled','latencyMs','status']);if(Object.keys(cmd).some(k=>!allowed.has(k)))fail('INVALID_INPUT');if(cmd.usage!==null){if(!cmd.usage||typeof cmd.usage!=='object'||Array.isArray(cmd.usage)||Object.keys(cmd.usage).some(k=>!['inputTokens','outputTokens','totalTokens','estimatedCostUsd'].includes(k)))fail('INVALID_INPUT');for(const key of ['inputTokens','outputTokens','totalTokens'] as const)integer(cmd.usage[key]);if(cmd.usage.totalTokens!==cmd.usage.inputTokens+cmd.usage.outputTokens)fail('INVALID_INPUT');if('estimatedCostUsd' in cmd.usage&&cmd.usage.estimatedCostUsd!==null&&(typeof cmd.usage.estimatedCostUsd!=='number'||!Number.isFinite(cmd.usage.estimatedCostUsd)||cmd.usage.estimatedCostUsd<0))fail('INVALID_INPUT');}const existing=this.all('agent_runs','AND request_id=?',[cmd.requestId])[0];if(existing){if(existing.actor_id!==this.actorId||existing.record_json!==canonical(cmd))fail('IDEMPOTENCY_CONFLICT')}else this.insert('agent_runs',{id:this.id('AGENT'),request_id:cmd.requestId,actor_id:this.actorId,status:cmd.status,record_json:canonical(cmd),created_at:this.now});break}
      default:fail('INVALID_INPUT');
    }
  }
  assertInvariants(){if(this.rows('PRAGMA foreign_key_check').length)fail('INVARIANT_VIOLATION');for(const p of this.pools())if(p.unallocatedQty<0)fail('INVARIANT_VIOLATION');for(const r of this.all('purchase_requests')){const a=this.all('allocation_sources',"AND request_id=? AND status!='released'",[r.id]).reduce((n,a)=>n+a.quantity,0);if(a!==0&&a!==r.quantity)fail('INVARIANT_VIOLATION')}for(const b of this.all('budget_ledger'))if(b.reserved_krw<0||b.secured_krw<0)fail('INVARIANT_VIOLATION')}
  dispatch(cmd:C.DemoCommand,ctx:C.CommandContext):C.CommandReceipt{this.check(ctx);if(!ctx.commandId)fail('INVALID_INPUT');const fingerprint=canonical({actorId:ctx.actorId,command:cmd});const old=this.all('command_results','AND id=?',[ctx.commandId])[0];if(old){if(old.actor_id!==ctx.actorId||old.fingerprint!==fingerprint)fail('IDEMPOTENCY_CONFLICT');return {...JSON.parse(old.result_json),effect:'replayed',snapshot:this.snapshot(ctx)}}if(ctx.expectedRevision!==undefined&&ctx.expectedRevision!==this.session().revision)fail('VERSION_CONFLICT');this.commandId=ctx.commandId;this.ids=[];this.eventIds=[];const generationBefore=this.generation;this.db.run('BEGIN');try{this.now=this.time();if(!['agent.record','notification.read'].includes(cmd.type))this.sweep();this.execute(cmd);if(!['agent.record','notification.read','need.record','recommendation.record','merchant.review','proposal.revise','proposal.undo'].includes(cmd.type))this.reconcile(this.automaticStores(cmd));this.assertInvariants();this.run('UPDATE sessions SET revision=revision+1 WHERE id=?',[this.sessionId]);const receipt={commandId:ctx.commandId,effect:'applied' as const,revision:this.session().revision,entityIds:[...new Set(this.ids)],eventIds:this.eventIds};this.insert('command_results',{id:ctx.commandId,actor_id:this.actorId,fingerprint,result_json:JSON.stringify(receipt)});this.db.run('COMMIT');return {...receipt,snapshot:this.snapshot(this.scope())}}catch(e){this.db.run('ROLLBACK');this.generation=generationBefore;throw e}}
  switchRole(actorId:string,scope:C.Scope){this.check(scope);this.one('actors',actorId);this.actorId=actorId;this.roleEpoch++;return this.snapshot(this.scope())}
  requestView(r:Row):C.RequestDetail{const consent=this.consent(r);const allocations=this.all('allocation_sources','AND request_id=?',[r.id]).map(a=>({id:a.id,lineId:a.line_id,quantity:a.quantity,status:a.status,received:this.one('order_lines',a.line_id).received_at!==null}));const reservations=this.all('reservations','AND request_id=? AND cycle=?',[r.id,r.payment_cycle]);const reservation=reservations[0]?dto(reservations[0]):null;const links=this.all('request_order_links','AND request_id=?',[r.id]).map(l=>({orderId:this.one('order_lines',l.line_id).order_id,lineId:l.line_id,quantity:l.quantity,active:Boolean(l.active),releasedReason:l.released_reason}));const payments=this.all('mock_payments','AND request_id=? ORDER BY cycle,attempt',[r.id]).map(dto);let pendingReason=r.pending_reason;if(r.status==='pending'&&!pendingReason){const condition=this.condition(r.store_id,r.sku),demand=this.demand(r.store_id).find(d=>d.sku===r.sku)!;pendingReason=condition.supply_status!=='available'?'supply_'+condition.supply_status:demand.pendingOrderCoverageQty>0?'awaiting_supply':condition.available_order_qty===0?'capacity_exhausted':demand.newOrderNeedQty<condition.minimum_order_qty?'below_minimum':'awaiting_order_review'}return {...dto(r),pendingReason,displayName:this.one('actors',r.actor_id).display_name,isActive:Boolean(r.is_active),consent:{accepted:true,...dto(consent),status:this.consentStatus(r)},links,allocations,payments,reservation,quantitySummary:{validPending:r.status==='pending'&&this.consentStatus(r)==='valid'?r.quantity:0,activeLinked:links.filter(l=>l.active).reduce((n,l)=>n+l.quantity,0),allocatedHeld:allocations.filter(a=>a.status==='held').reduce((n,a)=>n+a.quantity,0),paid:allocations.filter(a=>a.status==='paid').reduce((n,a)=>n+a.quantity,0),collected:reservation?.status==='collected'?r.quantity:0,pickupExpired:reservation?.status==='pickup_expired'?r.quantity:0}} as C.RequestDetail}
  snapshot(scope:C.Scope):C.DemoSnapshot{this.check(scope);this.now=this.time();const actor=this.actor(),merchant=actor.role==='merchant';const requests=this.all('purchase_requests',merchant?'AND store_id=? ORDER BY sequence':'AND actor_id=? ORDER BY sequence',[merchant?actor.store_id:actor.id]).map(r=>this.requestView(r));const orderIds=new Set(requests.flatMap(r=>r.links.map(l=>l.orderId)));const orders=this.all('orders',merchant?'AND store_id=?':'',merchant?[actor.store_id]:[]).filter(o=>merchant||orderIds.has(o.id)).map(o=>{const lines=this.all('order_lines','AND order_id=?',[o.id]).map(dto);return {...dto(o),status:lines.every(l=>l.receivedAt!==null)?'received':lines.every(l=>l.confirmedQty!==null)?'supply_confirmed':'submitted',lines}});const versions={schema:this.meta('schema'),seed:this.meta('seed'),catalog:this.meta('catalog'),catalogHash:this.meta('catalogHash'),policy:this.meta('policy')};const session=this.session();return {contractVersion:'domain-v1',versions,session:{id:this.sessionId,generation:this.generation,revision:session.revision,createdAt:session.created_at},actor:dto(actor),actors:this.all('actors').map(dto),roleEpoch:this.roleEpoch,clock:{now:this.now,offsetMs:session.clock_offset_ms,timeZone:'Asia/Seoul'},products:this.rows('SELECT * FROM products ORDER BY sku').map(dto),stores:this.rows('SELECT * FROM stores ORDER BY id').map(s=>({...dto(s),operatingStatus:'unverified'})),conditions:this.all('conditions',merchant?'AND store_id=?':'',merchant?[actor.store_id]:[]).map(c=>({...dto(c),simulated:true})),requests,orders,policies:merchant?[{...dto(this.policy(actor.store_id)),enabled:Boolean(this.policy(actor.store_id).enabled)}]:[],proposals:merchant?this.all('proposals','AND store_id=?',[actor.store_id]).map(dto):[],needs:this.all('need_records',merchant?'AND store_id=?':'AND actor_id=?',[merchant?actor.store_id:actor.id]).map(dto),notifications:this.all('notifications','AND actor_id=?',[actor.id]).map(dto),demand:merchant?this.demand(actor.store_id):[],budgets:merchant?[this.budget(actor.store_id)]:[],supplyPools:merchant?this.pools(actor.store_id):[],persistence:{status:'ready',durableRevision:session.revision}} as C.DemoSnapshot}
  query(query:C.DemoQuery,scope:C.Scope):unknown{const s=this.snapshot(scope);switch(query.type){case 'requests.list':return s.requests;case 'requests.detail':case 'merchant.requestDetail':if(query.type==='merchant.requestDetail')this.merchant();return s.requests.find(r=>r.id===query.requestId)??fail('NOT_FOUND');case 'merchant.demand':this.merchant();return s.demand;case 'merchant.productRequests':this.merchant();return s.requests.filter(r=>r.sku===query.sku);case 'catalog.storeOptions':return s.conditions.filter(c=>c.sku===query.sku);case 'notifications.list':return s.notifications;case 'needs.list':return s.needs;case 'recommendations.list':{const need=this.one('need_records',query.needId);const a=this.actor();if(a.role==='customer'?need.actor_id!==a.id:need.store_id!==a.store_id)fail('FORBIDDEN');return this.all('recommendation_events','AND need_id=?',[need.id]).map(dto)}case 'commands.result':{const result=this.all('command_results','AND id=?',[query.commandId])[0];if(!result)return null;if(result.actor_id!==this.actorId)fail('FORBIDDEN');return JSON.parse(result.result_json)}}}
}
