import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import initSqlJs from 'sql.js';
import { ProbeStore } from '../public/probe/core.mjs';
const SQL=await initSqlJs();
const seed=new Uint8Array(await readFile(new URL('../public/probe/seed.sqlite',import.meta.url)));
function harness(){let saved,fail=false; const store=new ProbeStore(SQL,seed,async value=>{if(fail)throw new Error('disk-full');saved=structuredClone(value);});return {store,get saved(){return saved;},set fail(value){fail=value;}};}
const note=(id='one',generation=0)=>({id,generation,actor:'customer',body:'사전점검 메모'});
test('real SQLite seed, insert, export/import and foreign keys restored',async()=>{const h=harness();await h.store.initialize();await h.store.add(note());const reopened=harness();await reopened.store.initialize(h.saved);assert.equal(reopened.store.state().notes[0].body,'사전점검 메모');assert.equal(reopened.store.state().foreignKeys,1);assert.throws(()=>reopened.store.db.run("INSERT INTO notes VALUES('bad','missing','x')"),/FOREIGN KEY/);});
test('SQL transaction rollback removes partial insert after constraint failure',()=>{const h=harness();const db=h.store.open(seed);db.run('BEGIN');db.run("INSERT INTO notes VALUES('partial','customer','x')");assert.throws(()=>db.run("INSERT INTO notes VALUES('bad','customer','')"),/CHECK/);db.run('ROLLBACK');assert.equal(db.exec('SELECT * FROM notes').length,0);db.close();});
test('snapshot failure restores prior successful snapshot and recovers',async()=>{const h=harness();await h.store.initialize();await h.store.add(note());h.fail=true;await assert.rejects(h.store.add(note('failed')),/disk-full/);assert.deepEqual(h.store.state().notes.map(n=>n.id),['one']);assert.equal(h.store.state().foreignKeys,1);h.fail=false;await h.store.add(note('retry'));assert.equal(h.store.state().notes.length,2);});
test('first storage failure prevents further writes until successful reset',async()=>{const h=harness();h.fail=true;await assert.rejects(h.store.initialize(),/disk-full/);assert.equal(h.store.state().writable,false);await assert.rejects(h.store.add(note()),/STORAGE_NOT_READY/);h.fail=false;await h.store.reset();await h.store.add(note('ready',1));assert.equal(h.store.state().notes.length,1);});
test('reset persists generation and rejects delayed old commands',async()=>{const h=harness();await h.store.initialize();await h.store.add(note());await h.store.reset();assert.equal(h.store.state().notes.length,0);assert.equal(h.saved.generation,1);await assert.rejects(h.store.add(note('late',0)),/STALE_GENERATION/);await h.store.add(note('new',1));assert.equal(h.store.state().notes.length,1);});
test('failed reset preserves generation and saved records',async()=>{const h=harness();await h.store.initialize();await h.store.add(note());h.fail=true;await assert.rejects(h.store.reset(),/disk-full/);assert.equal(h.store.state().generation,0);assert.equal(h.store.state().notes.length,1);});
test('duplicate command is idempotent; conflict and invalid input are rejected',async()=>{const h=harness();await h.store.initialize();await h.store.add(note());await h.store.add(note());assert.equal(h.store.state().notes.length,1);await assert.rejects(h.store.add({...note(),body:'different'}),/ID_CONFLICT/);await assert.rejects(h.store.add({...note('bad'),actor:'invalid'}),/INVALID_INPUT/);await assert.rejects(h.store.add({...note('empty'),body:'  '}),/INVALID_INPUT/);assert.equal(h.store.state().notes.length,1);});
test('incompatible or corrupt snapshots fail explicitly without overwriting',async()=>{const h=harness();await h.store.initialize();const bad=harness();await assert.rejects(bad.store.initialize({...h.saved,seed:'future'}),/SNAPSHOT_VERSION/);assert.equal(bad.saved,undefined);await assert.rejects(bad.store.initialize({...h.saved,bytes:new Uint8Array([1,2,3])}));assert.equal(bad.saved,undefined);await bad.store.reset();assert.equal(bad.store.state().notes.length,0);});
