'use client';
import {useEffect,useRef,useState} from 'react';
import type {DemoClient,DemoCommand,DemoSnapshot,PolicyView,ProposalView,RequestDetail} from '../../contracts/domain';
import type {AssistantResponse,DialogueTurn,MerchantConstraints,MerchantInterpretation} from '../../contracts/assistant';
import {date,krw,proposalChange,toModelConstraints} from './model';
import s from './merchant.module.css';
type Props={snapshot:DemoSnapshot;client:DemoClient;onSnapshot:(value:DemoSnapshot)=>void};
type PolicyCap=PolicyView;
const scope=(v:DemoSnapshot)=>({sessionId:v.session.id,generation:v.session.generation,actorId:v.actor.id,roleEpoch:v.roleEpoch});
const same=(a:DemoSnapshot,b:DemoSnapshot)=>a.session.id===b.session.id&&a.session.generation===b.session.generation&&a.actor.id===b.actor.id&&a.roleEpoch===b.roleEpoch&&a.versions.catalogHash===b.versions.catalogHash;
const requestStatus:Record<string,string>={pending:'수요 접수',review_required:'다시 확인 필요',allocated:'물량 배정',reserved:'결제·예약',cancelled:'취소',confirmed:'입고 대기',payment_failed:'모의 결제 실패',pickup_ready:'픽업 가능',collected:'수령 완료',pickup_expired:'픽업 기한 종료'};
export function MerchantView({snapshot,client,onSnapshot}:Props){
 const ref=useRef(snapshot);ref.current=snapshot;
 const [tab,setTab]=useState<'demand'|'orders'|'needs'|'policy'>('demand');
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[text,setText]=useState('');
 const [history,setHistory]=useState<DialogueTurn[]>([]),[answer,setAnswer]=useState<MerchantInterpretation|null>(null),[previous,setPrevious]=useState<MerchantConstraints|null>(null);
 const [answerProposal,setAnswerProposal]=useState<{id:string;version:number}|null>(null),[detail,setDetail]=useState<string|null>(null),[collection,setCollection]=useState('');
 const [modelLabel,setModelLabel]=useState(''),[supply,setSupply]=useState<Record<string,string>>({});
 const [budget,setBudget]=useState('100000'),[enabled,setEnabled]=useState(false),[cap,setCap]=useState(''),[policyConsent,setPolicyConsent]=useState(false),[exclude,setExclude]=useState<string[]>([]);
 const lock=useRef(false),revision=useRef(0),abort=useRef<AbortController|null>(null),conversation=useRef('');
 const store=snapshot.stores.find(x=>x.id===snapshot.actor.storeId);
 const policy=snapshot.policies.find(p=>p.storeId===snapshot.actor.storeId) as PolicyCap|undefined;
 const proposal=[...snapshot.proposals].reverse().find(p=>p.status==='draft'&&p.storeId===snapshot.actor.storeId)||null;
 const budgetView=snapshot.budgets.find(b=>b.storeId===snapshot.actor.storeId);
 const products=new Map(snapshot.products.map(p=>[p.sku,p]));
 useEffect(()=>{setText('');setHistory([]);setAnswer(null);setAnswerProposal(null);setPrevious(null);setPolicyConsent(false);setError('');setNotice('');revision.current++;conversation.current=crypto.randomUUID();abort.current?.abort();},[snapshot.session.id,snapshot.actor.id,snapshot.roleEpoch,snapshot.session.generation,snapshot.versions.catalogHash]);
 useEffect(()=>()=>abort.current?.abort(),[]);
 useEffect(()=>{if(policy){setBudget(String(policy.dailyBudgetKrw));setEnabled(policy.enabled);setCap(policy.maxQuantityPerReview==null?'':String(policy.maxQuantityPerReview));setPolicyConsent(false);setExclude(snapshot.products.filter(p=>(policy.skuScope.length&&!policy.skuScope.includes(p.sku))||(policy.categoryScope.length&&!policy.categoryScope.includes(p.category))).map(p=>p.sku));}},[policy?.version,snapshot.actor.id,snapshot.roleEpoch,snapshot.session.generation]);
 async function command(value:DemoCommand,message?:string){
  if(lock.current)return null;lock.current=true;setBusy(true);setError('');setNotice('');const captured=ref.current;
  try{const id=crypto.randomUUID();const result=await client.dispatch(value,{...scope(captured),commandId:id,correlationId:id});
   if(!same(captured,ref.current))return null;
   if(result.ok){onSnapshot(result.data.snapshot);ref.current=result.data.snapshot;if(message)setNotice(message);return result.data.snapshot}
   setError(result.error.message);return null;
  }catch{setError('처리 결과를 확인하지 못했어요. 최신 상태를 다시 확인해 주세요.');return null}
  finally{lock.current=false;setBusy(false)}
 }
 async function review(){if(!store)return;const result=await command({type:'merchant.review',storeId:store.id},'현재 수요와 조건으로 검토안을 갱신했어요.');if(result){setAnswer(null);setAnswerProposal(null)}}
 async function ask(){
  if(lock.current||!text.trim()||!store)return;const captured=ref.current;const current=proposal;const input=text.trim();const version=++revision.current;const requestId=crypto.randomUUID();const request={...scope(captured),requestId,conversationId:conversation.current||crypto.randomUUID(),inputRevision:version,catalogHash:captured.versions.catalogHash,text:input,history:history.slice(-10),state:{storeId:store.id,proposalId:current?.id??null,proposalVersion:current?.version??null,currentProposalVersion:current?.version??null,stale:false,dailyBudgetKrw:policy?.dailyBudgetKrw??0,currentConstraints:toModelConstraints(current),previousConstraints:previous,groups:captured.demand.slice(0,60).map(row=>({sku:row.sku,requestedQty:row.validPendingQty,orderableQty:row.newOrderNeedQty,purchaseCostKrw:captured.conditions.find(c=>c.sku===row.sku&&c.storeId===store.id)?.purchaseCostKrw??0}))}};
  lock.current=true;setBusy(true);setError('');setAnswer(null);abort.current=new AbortController();
  try{const response=await fetch('/api/merchant-assistant',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(request),signal:abort.current.signal});const body=await response.json() as AssistantResponse<MerchantInterpretation>;
   if(!same(captured,ref.current)||version!==revision.current)return;
   if(!body.ok){setError(body.error.message);const attempt=body.error.attempt;if(attempt){const id=crypto.randomUUID();const logged=await client.dispatch({type:'agent.record',requestId,mode:attempt.mode,model:attempt.model||'unknown',promptVersion:'unavailable',catalogHash:captured.versions.catalogHash,providerCalled:attempt.providerCalled,usage:attempt.usage,latencyMs:attempt.latencyMs,status:'lookup_error'},{...scope(captured),commandId:id,correlationId:requestId});if(logged.ok&&same(captured,ref.current)){onSnapshot(logged.data.snapshot);ref.current=logged.data.snapshot}}return}
   const data=body.data;if(data.requestId!==requestId||data.conversationId!==request.conversationId||data.inputRevision!==version||data.catalogHash!==captured.versions.catalogHash||data.actorId!==captured.actor.id||data.sessionId!==captured.session.id||data.generation!==captured.session.generation||data.roleEpoch!==captured.roleEpoch){setError('이전 화면의 응답이어서 반영하지 않았어요. 다시 말씀해 주세요.');return}
   const id=crypto.randomUUID();const logged=await client.dispatch({type:'agent.record',requestId,mode:data.mode,model:data.model,promptVersion:data.promptVersion,catalogHash:data.catalogHash,usage:data.usage,providerCalled:data.mode==='live',latencyMs:data.latencyMs,status:'ok'}, {...scope(captured),commandId:id,correlationId:requestId});if(!same(captured,ref.current)||version!==revision.current)return;if(!logged.ok){setError('AI 해석 기록을 저장하지 못했어요. 입력을 유지했으니 다시 시도해 주세요. '+logged.error.message);return}onSnapshot(logged.data.snapshot);ref.current=logged.data.snapshot;
setAnswer(data.result);setAnswerProposal(current?{id:current.id,version:current.version}:null);setModelLabel(`${data.mode==='live'?'실제 AI':'고정 테스트 응답'} · ${(data.latencyMs/1000).toFixed(1)}초`);setHistory(old=>[...old,{role:'user',content:input},{role:'assistant',content:JSON.stringify(data.result)}]);setText('');
  }catch(e){if(same(captured,ref.current)&&!(e instanceof DOMException&&e.name==='AbortError'))setError('모델 연결이 원활하지 않아요. 입력을 유지했으니 다시 시도해 주세요.');}
  finally{lock.current=false;setBusy(false)}
 }
 async function applyAnswer(){if(!answer||answer.intent==='clarify')return;
  if(answer.scope==='policy'){
   if(answer.constraints.maxQuantity===0){setError('지속 정책의 수량은 1개 이상으로 정해 주세요. 발주를 멈추려면 정책을 꺼 주세요.');return}
   setBudget(String(answer.constraints.budgetLimitKrw??policy?.dailyBudgetKrw??100000));setCap(answer.constraints.maxQuantity===null?String(policy?.maxQuantityPerReview??''):String(answer.constraints.maxQuantity));setExclude(snapshot.products.filter(p=>answer.constraints.excludeProductIds.includes(p.sku)||answer.constraints.excludeCategories.includes(p.category)||(policy?.skuScope.length&&!policy.skuScope.includes(p.sku))||(policy?.categoryScope.length&&!policy.categoryScope.includes(p.category))).map(p=>p.sku));setEnabled(true);setPolicyConsent(false);setTab('policy');setNotice('정책 초안을 옮겼어요. 모든 조건을 확인한 뒤 별도로 승인해 주세요.');return;
  }
  if(!proposal||!answerProposal||proposal.id!==answerProposal.id||proposal.version!==answerProposal.version){setError('검토안이 바뀌었어요. 최신 검토안을 다시 확인해 주세요.');return}
  setPrevious(toModelConstraints(proposal));const updated=await command(answer.intent==='restore'?{type:'proposal.undo',proposalId:proposal.id,expectedProposalVersion:proposal.version}:{type:'proposal.revise',proposalId:proposal.id,expectedProposalVersion:proposal.version,change:proposalChange(proposal,answer.constraints)},'이번 검토안에만 반영했어요. 발주 승인은 아직 하지 않았어요.');if(updated)setAnswer(null);
 }
 function constraintsDescription(c:MerchantConstraints){return [c.budgetLimitKrw!==null?`예산 ${krw(c.budgetLimitKrw)}`:null,c.excludeCategories.length?`${c.excludeCategories.join(', ')} 제외`:null,c.excludeProductIds.length?`${c.excludeProductIds.map(id=>products.get(id)?.name||id).join(', ')} 제외`:null,c.maxQuantity!==null?`상품별 최대 ${c.maxQuantity}개`:null,c.restorePrevious?'이전 수정으로 되돌리기':null].filter(Boolean).join(' · ')}
 const scopeCategory=[...new Set(snapshot.products.map(p=>p.category))];
 return <section className={s.wrap} aria-label="경영주 업무"><div className={s.title}><div><span className={s.eyebrow}>STORE DESK</span><h1>모인 마음을, 한 번에.</h1><p>{store?.name} <span>· 점포 위치 참고 / 모든 거래는 모의</span></p></div><span className={s.status}>{policy?.enabled?'자동발주 켜짐':'직접 검토 중'}</span></div>
 <div className={s.metrics}><div><span>유효 미확보 수요</span><strong>{snapshot.demand.reduce((n,r)=>n+r.validPendingQty,0)}<small>개</small></strong></div><div><span>진행 중 발주</span><strong>{snapshot.orders.filter(o=>o.status!=='received').length}<small>건</small></strong></div><div><span>오늘 발주 예산 사용</span><strong>{krw(budgetView?.usedKrw||0)}</strong><small>한도 {krw(policy?.dailyBudgetKrw||0)} · 매입가 기준</small></div><div><span>픽업 준비 완료</span><strong>{snapshot.requests.filter(r=>r.reservation?.status==='pickup_ready').length}<small>건</small></strong></div></div>
 <nav className={s.tabs} aria-label="경영주 업무 메뉴">{([['demand','수요·발주'],['orders','주문·픽업'],['needs','미충족 니즈'],['policy','자동발주 정책']] as const).map(([id,label])=><button type="button" key={id} aria-current={tab===id?'page':undefined} onClick={()=>{setTab(id);setError('')}}>{label}</button>)}</nav>
 {error&&<div role="alert" className={s.error}>{error}</div>}{notice&&<div role="status" className={s.notice}>{notice}</div>}
 {tab==='demand'&&<><div className={s.panel}><div className={s.heading}><div><h2>이번 묶음 검토</h2><p>유효 요청에서 기존 발주·확보량을 뺀 수량만 제안해요.</p></div><button disabled={busy} onClick={review}>{busy?'처리 중…':'최신 수요 검토'}</button></div>
 {snapshot.demand.length===0?<div className={s.empty}><strong>아직 모인 요청이 없어요.</strong><p>고객 화면에서 상품과 점포를 확인하고 구매 동의까지 마치면 이곳에 수요가 모여요.</p></div>:<div className={s.tableScroll}><table><thead><tr><th>상품</th><th>미확보</th><th>기존 발주</th><th>새 발주안</th><th>매입 금액</th><th>요청 상세</th></tr></thead><tbody>{snapshot.demand.map(row=>{const line=proposal?.lines.find(l=>l.sku===row.sku);return <tr key={row.sku}><td><strong>{products.get(row.sku)?.name||row.sku}</strong><small>{row.deferredReasons.join(' · ')||'고객 확인·동의 수요'}</small></td><td>{row.validPendingQty}개</td><td>{row.pendingOrderCoverageQty}개</td><td>{line?`${line.quantity}개`:'보류 / 미검토'}</td><td>{line?krw(line.totalKrw):'—'}</td><td><button className={s.link} onClick={()=>setDetail(detail===row.sku?null:row.sku)}>고객 {snapshot.requests.filter(r=>r.sku===row.sku).length}건</button></td></tr>})}</tbody></table></div>}
 {proposal&&<><div className={s.approval}><div><strong>{proposal.lines.length}개 상품 · {proposal.lines.reduce((n,l)=>n+l.quantity,0)}개</strong><span>모의 발주 합계 {krw(proposal.totalKrw)}</span></div><button className={s.primary} disabled={busy||!proposal.lines.length} onClick={()=>command({type:'proposal.approve',proposalId:proposal.id,expectedProposalVersion:proposal.version,confirmed:true},'묶음 발주를 승인했어요. 공급 확정과 입고는 주문 화면에서 이어서 확인해 주세요.')}>이 묶음 발주 승인</button></div>{proposal.deferred.length>0&&<details className={s.deferred}><summary>보류 {proposal.deferred.length}개 상품 · 이유와 다음 행동</summary>{proposal.deferred.map((d,i)=><p key={d.sku+i}><strong>{products.get(d.sku)?.name}</strong> — {d.reason}<br/><small>{d.nextAction}</small></p>)}</details>}</>}
 </div>{detail&&<div className={s.panel}><div className={s.heading}><h2>{products.get(detail)?.name} · 고객 요청</h2><button onClick={()=>setDetail(null)}>상세 닫기</button></div>{snapshot.requests.filter(r=>r.sku===detail).map(r=><RequestCard key={r.id} value={r}/>)}</div>}
 <div className={s.assistant}><div><span className={s.eyebrow}>말로 다듬는 검토안</span><h2>“이번에는 5만원 안에서만.”</h2><p>이번 묶음 수정과 앞으로의 정책 변경을 나눠 확인해요.</p></div><form onSubmit={e=>{e.preventDefault();ask()}}><label htmlFor="merchant-instruction">어떻게 바꿀까요?</label><div className={s.inputRow}><input id="merchant-instruction" value={text} maxLength={1200} onChange={e=>{setText(e.target.value);revision.current++;setAnswer(null)}} placeholder="예산, 제외할 상품, 이번만 또는 앞으로의 조건"/><button className={s.primary} disabled={busy||!text.trim()}>{busy?'해석 중…':'변경안 보기'}</button></div></form>
 {answer&&<div className={s.answer}><small>{modelLabel} · 아직 실행하지 않은 제안</small><h3>{answer.intent==='clarify'?'조금 더 알려주세요':answer.scope==='policy'?'앞으로 적용할 정책 초안':'이번 묶음의 변경안'}</h3><p>{answer.question||answer.reason}</p>{answer.intent!=='clarify'&&<><p><strong>{constraintsDescription(answer.constraints)}</strong></p><button disabled={busy} onClick={applyAnswer}>{answer.scope==='policy'?'정책 확인 화면으로':'이번 검토안에 반영'}</button></>}</div>}
 </div></>}
 {tab==='orders'&&<><div className={s.panel}><h2>픽업 수령 확인</h2><p>입고 알림부터 48시간 안에, 고객의 예약 번호로 확인해요.</p><form className={s.inputRow} onSubmit={e=>{e.preventDefault();command({type:'merchant.collect',reservationCode:collection.trim()},'수령 완료로 기록했어요.')}}><label className={s.sr} htmlFor="pickup-code">고객 예약 번호</label><input id="pickup-code" value={collection} onChange={e=>setCollection(e.target.value)} placeholder="예약 번호 입력"/><button className={s.primary} disabled={busy||!collection.trim()}>수령 완료 처리</button></form></div>
 {snapshot.orders.length===0?<div className={s.panel}><p>아직 발주한 주문이 없어요.</p></div>:snapshot.orders.map(order=><div className={s.panel} key={order.id}><div className={s.heading}><div><h2>발주 {order.id.slice(-8)}</h2><p>{date(order.createdAt)} · {order.approvalType==='policy'?'승인된 정책으로 자동발주':'묶음 수동 승인'}</p></div><span className={s.status}>{order.status==='received'?'입고 완료':order.status==='supply_confirmed'?'공급 확정':'공급 확인 중'}</span></div>{order.lines.map(line=><div className={s.orderLine} key={line.id}><div><strong>{products.get(line.sku)?.name}</strong><p>발주 {line.orderedQty}개 · 확보 {line.confirmedQty===null?'미확정':`${line.confirmedQty}개`} · 입고 {line.receivedQty===null?'대기':`${line.receivedQty}개`}</p><small>발주 매입가 {krw(line.purchaseCostKrw)} / 고객 확인 판매가 {krw(line.salePriceKrw)}</small></div>{line.confirmedQty===null?<div className={s.controls}><label>모의 공급 확정량 <input type="number" min={0} max={line.orderedQty} value={supply[line.id]??String(line.orderedQty)} onChange={e=>setSupply(old=>({...old,[line.id]:e.target.value}))}/></label><button disabled={busy} onClick={()=>command({type:'demo.confirmSupply',lineId:line.id,confirmedQty:Number(supply[line.id]??line.orderedQty)},'공급량을 확정했어요. 유효 동의가 있는 요청에 접수 순서대로 배정·모의 결제를 처리했어요.')}>공급 확정</button></div>:line.receivedQty===null?<button disabled={busy} onClick={()=>command({type:'demo.receive',lineId:line.id,receivedQty:line.confirmedQty!},'입고를 기록했어요. 준비된 예약에는 픽업 알림과 48시간 기한이 생성됐어요.')}>확보 {line.confirmedQty}개 입고 기록</button>:<span>입고 {date(line.receivedAt)}</span>}</div>)}</div>)}
 <div className={s.panel}><h2>예약·픽업 현황</h2>{snapshot.requests.filter(r=>r.reservation).map(r=><RequestCard key={r.id} value={r}/>)}{!snapshot.requests.some(r=>r.reservation)&&<p>아직 예약이 없어요. 물량 확보와 모의 결제를 마치면 표시됩니다.</p>}</div></>}
 {tab==='needs'&&<div className={s.panel}><h2>고객이 남긴 미충족 니즈</h2><p>관심과 미식별 기록입니다. 구매 확약이나 자동발주 수량에 더하지 않아요.</p>{snapshot.needs.length===0?<p className={s.empty}>아직 남겨진 니즈가 없어요.</p>:snapshot.needs.map(need=><article className={s.need} key={need.id}><span>{date(need.createdAt)} · {need.identificationStatus}</span><h3>{need.originalText}</h3><p>{need.reason}</p><small>확인 단서: {need.extractedClues.join(' · ')||'추가 확인 필요'}</small></article>)}</div>}
 {tab==='policy'&&<div className={s.panel}><h2>자동발주는 승인한 조건 안에서만</h2><p>유효 미확보 수요 · 접수 순서 · 현재 공급량 · 최소 발주량과 배수 · 남은 예산을 매번 다시 확인해요.</p><form onSubmit={async e=>{e.preventDefault();if(!policy||!store||!policyConsent)return;const allowed=snapshot.products.filter(p=>!exclude.includes(p.sku)).map(p=>p.sku);if(enabled&&!allowed.length){setError('발주할 상품을 한 개 이상 포함하거나 정책을 꺼 주세요.');return}const result=await command({type:'policy.update',storeId:store.id,expectedPolicyVersion:policy.version,enabled,skuScope:exclude.length?allowed:[],categoryScope:[],dailyBudgetKrw:Number(budget),confirmed:true,maxQuantityPerReview:cap===''?null:Number(cap)},'확인한 정책을 저장했어요. 자동발주는 승인된 범위에서만 처리됩니다.');if(result){setPolicyConsent(false);setAnswer(null)}}}>
 <div className={s.policyFields}><label className={s.check}><input type="checkbox" checked={enabled} onChange={e=>{setEnabled(e.target.checked);setPolicyConsent(false)}}/>자동발주 활성화</label><label>하루 매입 예산(원)<input type="number" min={budgetView?.usedKrw||0} step={1} value={budget} onChange={e=>{setBudget(e.target.value);setPolicyConsent(false)}} required/></label><label>검토 한 번마다 상품별 최대 수량<input type="number" min={1} step={1} value={cap} onChange={e=>{setCap(e.target.value);setPolicyConsent(false)}} placeholder="추가 상한 없음"/><small>하루 누적 상한이 아닙니다. 다음 새 검토에서 추가 발주할 수 있어요.</small></label></div>
 <fieldset className={s.categories}><legend>제외할 상품군</legend>{scopeCategory.map(category=>{const skus=snapshot.products.filter(p=>p.category===category).map(p=>p.sku);const checked=skus.every(id=>exclude.includes(id));return <label className={s.check} key={category}><input type="checkbox" checked={checked} onChange={e=>{setExclude(old=>e.target.checked?[...new Set([...old,...skus])]:old.filter(id=>!skus.includes(id)));setPolicyConsent(false)}}/>{category}</label>})}</fieldset>
 <details className={s.deferred}><summary>개별 제외 상품 {exclude.length}개 확인</summary>{exclude.map(id=><span className={s.chip} key={id}>{products.get(id)?.name}<button type="button" aria-label={`${products.get(id)?.name} 제외 해제`} onClick={()=>{setExclude(old=>old.filter(x=>x!==id));setPolicyConsent(false)}}>×</button></span>)}</details>
 <div className={s.policySummary}><strong>{enabled?'자동발주 켜기':'자동발주 끄기'}</strong><p>하루 예산 {krw(Number(budget)||0)} · 제외 {exclude.length}상품 · {cap?`검토당 상품별 최대 ${cap}개`:'추가 수량 상한 없음'}</p><p>수요보다 많이 채우지 않으며, 조건을 충족하지 못하면 보류해요. 앱이 열려 있을 때만 동작합니다.</p></div>
 <label className={s.check}><input type="checkbox" checked={policyConsent} onChange={e=>setPolicyConsent(e.target.checked)}/>위 상품 범위·예산·수량 조건으로 정책을 변경하는 데 동의합니다.</label><button className={s.primary} disabled={busy||!policyConsent||!policy}>이 조건으로 정책 승인</button>
 </form></div>}
 </section>;
}
function RequestCard({value:r}:{value:RequestDetail}){return <details className={s.request}><summary><strong>{r.displayName} · {r.quantity}개</strong><span>{requestStatus[r.reservation?.status||r.status]||r.status}</span><span>접수 {r.sequence}번</span></summary><dl className={s.detailGrid}><div><dt>고객 확인 가격</dt><dd>{krw(r.acceptedPriceKrw)} / 개</dd></div><div><dt>구매 동의</dt><dd>{r.consent.status==='valid'?'유효':r.consent.status==='not_applicable_paid'?'결제 완료 후 동의 만료 미적용':r.consent.status} · v{r.consent.version}</dd></div><div><dt>동의 시각 · 만료</dt><dd>{date(r.consent.consentAt)} → {date(r.consent.expiresAt)}</dd></div><div><dt>발주 연결</dt><dd>{r.links.filter(l=>l.active).map(l=>`${l.orderId.slice(-8)} / ${l.quantity}개`).join(', ')||'활성 연결 없음'}</dd></div><div><dt>확보·배정</dt><dd>{r.allocations.filter(a=>a.status!=='released').map(a=>`${a.quantity}개 ${a.status==='paid'?'결제 귀속':'결제 대기 보관'}`).join(', ')||'아직 없음'}</dd></div><div><dt>모의 결제</dt><dd>{r.payments.map(p=>`${p.attempt}회 ${p.status==='succeeded'?'성공':'실패'} (${krw(p.amountKrw)})`).join(' · ')||'미실행'}</dd></div><div><dt>예약 번호</dt><dd>{r.reservation?.code||'아직 없음'}</dd></div><div><dt>픽업 알림 · 마감</dt><dd>{date(r.reservation?.pickupAvailableAt??null)} → {date(r.reservation?.pickupDeadlineAt??null)}</dd></div><div><dt>수령</dt><dd>{date(r.reservation?.collectedAt??null)}</dd></div></dl>{r.pendingReason&&<p>{r.pendingReason}</p>}<small>요청 {r.id} · {r.sku}</small></details>}
