import type { SqlJsStatic } from 'sql.js';
import { DomainEngine, DomainFailure } from '../domain/engine';
import type { CommandContext, DemoCommand, DemoQuery, DemoSnapshot, Result, Scope, Versions } from '../contracts/domain';
export interface SnapshotEnvelope { bytes:Uint8Array; versions:Versions; sessionId:string; generation:number; actorId:string; roleEpoch:number; revision:number }
export interface SnapshotStore { read():Promise<SnapshotEnvelope|null>; write(value:SnapshotEnvelope):Promise<void> }
export type WorkerOperation = {operation:'initialize'}|{operation:'snapshot';scope:Scope}|{operation:'query';scope:Scope;query:DemoQuery}|{operation:'switchRole';scope:Scope;actorId:string}|{operation:'command';context:CommandContext;command:DemoCommand};
export class DemoRuntime {
  engine!:DomainEngine;private durable:SnapshotEnvelope|null=null;private queue:Promise<unknown>=Promise.resolve();private initialized=false;private recoveryGeneration=2;
  constructor(private SQL:SqlJsStatic,private seed:Uint8Array,private store:SnapshotStore,private versions:Versions,private clock:()=>number=Date.now){}
  private open(bytes:Uint8Array,actorId?:string,roleEpoch=0,sessionId='DEMO-SESSION-001'){this.engine?.db.close();this.engine=new DomainEngine(new this.SQL.Database(bytes),this.clock,sessionId);if(actorId)this.engine.actorId=actorId;this.engine.roleEpoch=roleEpoch;this.engine.assertInvariants()}
  private envelope():SnapshotEnvelope{const e=this.engine;const bytes=e.db.export();e.db.run('PRAGMA foreign_keys=ON');return {bytes,versions:this.versions,sessionId:e.sessionId,generation:e.generation,actorId:e.actorId,roleEpoch:e.roleEpoch,revision:e.session().revision}}
  private async save(){const candidate=this.envelope();try{await this.store.write(candidate);this.durable=candidate}catch{if(this.durable)this.open(this.durable.bytes,this.durable.actorId,this.durable.roleEpoch,this.durable.sessionId);else this.open(this.seed);throw new DomainFailure('PERSISTENCE_FAILED','데모 저장에 실패했습니다. 마지막 저장 상태로 복구했습니다.',true)}}
  async perform(op:WorkerOperation):Promise<Result<unknown>>{const run=async()=>{try{if(op.operation==='initialize'){if(!this.initialized){const saved=await this.store.read();if(saved){this.recoveryGeneration=saved.generation+1;if(saved.versions.schema!==this.versions.schema||saved.versions.seed!==this.versions.seed||saved.versions.catalogHash!==this.versions.catalogHash)throw new DomainFailure('SNAPSHOT_INCOMPATIBLE');try{this.open(saved.bytes,saved.actorId,saved.roleEpoch,saved.sessionId)}catch{throw new DomainFailure('SNAPSHOT_CORRUPT')}this.durable=saved}else this.open(this.seed);this.engine.now=this.engine.time();this.engine.db.run('BEGIN');try{this.engine.reconcile();this.engine.assertInvariants();this.engine.db.run('COMMIT')}catch(e){this.engine.db.run('ROLLBACK');throw e}await this.save();this.initialized=true}return {ok:true,data:this.engine.snapshot(this.engine.scope())} as const}
        if(!this.initialized)throw new DomainFailure('NOT_INITIALIZED');if(op.operation==='snapshot')return {ok:true,data:this.engine.snapshot(op.scope)} as const;if(op.operation==='query')return {ok:true,data:this.engine.query(op.query,op.scope)} as const;if(op.operation==='switchRole'){this.engine.switchRole(op.actorId,op.scope);await this.save();return {ok:true,data:this.engine.snapshot(this.engine.scope())} as const}
        const receipt=this.engine.dispatch(op.command,op.context);await this.save();receipt.snapshot=this.engine.snapshot(this.engine.scope());return {ok:true,data:receipt} as const;
      }catch(error){const known=error instanceof DomainFailure;return {ok:false,error:{code:known?error.code:'DOMAIN_FAILURE',message:known&&error.message!==error.code?error.message:'처리하지 못했습니다. 현재 상태를 확인해 주세요.',retryable:known?error.retryable:false}} as const}};const result=this.queue.then(run,run);this.queue=result;return result}
  /** Explicit recovery after the UI explains corrupt/incompatible data. Never automatic. */
  async resetIncompatible(confirmed:boolean):Promise<Result<DemoSnapshot>>{if(this.initialized)return {ok:false,error:{code:'FORBIDDEN',message:'현재 세션의 초기화 메뉴를 사용해 주세요.',retryable:false}};if(confirmed!==true)return {ok:false,error:{code:'INVALID_INPUT',message:'초기화를 확인해 주세요.',retryable:false}};const task=async()=>{try{this.open(this.seed);this.engine.run('UPDATE sessions SET generation=? WHERE id=?',[this.recoveryGeneration,this.engine.sessionId]);this.engine.generation=this.recoveryGeneration;this.engine.seedMutable();this.engine.roleEpoch++;await this.save();this.initialized=true;return {ok:true,data:this.engine.snapshot(this.engine.scope())} as const}catch{return {ok:false,error:{code:'PERSISTENCE_FAILED',message:'초기화 저장에 실패했습니다.',retryable:true}} as const}};const result=this.queue.then(task,task);this.queue=result;return result}
}
export class IndexedDbSnapshotStore implements SnapshotStore {
  constructor(private namespace='wanna-gs-demo-v1'){}
  private open():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const request=indexedDB.open(this.namespace,1);request.onupgradeneeded=()=>request.result.createObjectStore('snapshots');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
  async read(){const db=await this.open();return new Promise<SnapshotEnvelope|null>((resolve,reject)=>{const tx=db.transaction('snapshots','readonly');const r=tx.objectStore('snapshots').get('current');let value:SnapshotEnvelope|null=null;r.onsuccess=()=>{value=r.result??null};tx.oncomplete=()=>{db.close();resolve(value)};tx.onabort=tx.onerror=()=>{db.close();reject(tx.error)}})}
  async write(value:SnapshotEnvelope){const db=await this.open();return new Promise<void>((resolve,reject)=>{const tx=db.transaction('snapshots','readwrite');tx.objectStore('snapshots').put(value,'current');tx.oncomplete=()=>{db.close();resolve()};tx.onabort=tx.onerror=()=>{db.close();reject(tx.error??new Error('snapshot aborted'))}})}
}
