import type {DemoSnapshot,RequestDetail,SourceOrigin} from '../../src/contracts/domain';
const origin:SourceOrigin={kind:'synthetic',sourceIds:['merchant-independent-fixture'],sourceUrls:[],checkedAt:null,publishedAt:null,productConfidence:'fixture',trendConfidence:'not_claimed',fieldOrigin:{},researchCaseIds:['R-MERCHANT-BATCH-01']};
export const NOW=1800000000000;
export function fixtureSnapshot():DemoSnapshot{
 const products=Array.from({length:10},(_,i)=>({sku:`p${i}`,name:`합성 ${i<5?'빵':'음료'} ${i+1}`,category:i<5?'빵':'음료',brand:'테스트',size:'1개',flavor:null,aliases:[],attributes:{observedNameTerms:[]},sourceOrigin:origin}));
 const requests:RequestDetail[]=products.map((p,i)=>({id:`r${i}`,actorId:`c${i}`,displayName:`합성 고객 ${i+1}`,sku:p.sku,storeId:'s0',quantity:2,acceptedPriceKrw:2000,sequence:i+1,status:'pending',isActive:true,pendingReason:null,consent:{accepted:true,version:1,termsVersion:'fixture',sku:p.sku,storeId:'s0',quantity:2,unitPriceKrw:2000,consentAt:NOW,expiresAt:NOW+7*86400000,status:'valid'},createdAt:NOW,updatedAt:NOW,version:1,paymentCycle:1,links:[],allocations:[],payments:[],reservation:null,quantitySummary:{validPending:2,activeLinked:0,allocatedHeld:0,paid:0,collected:0,pickupExpired:0}}));
 const lines=products.map(p=>({sku:p.sku,quantity:2,purchaseCostKrw:1000,salePriceKrw:2000,conditionVersion:1,totalKrw:2000}));
 return {contractVersion:'domain-v1',versions:{schema:'fixture-v1',seed:'merchant-fixture10',catalog:'fixture10',catalogHash:'fixture-catalog-A',policy:'ADR005-fixture'},session:{id:'fixture-session',generation:1,revision:1,createdAt:NOW},actor:{id:'m0',role:'merchant',displayName:'합성 경영주',storeId:'s0'},actors:[],roleEpoch:1,clock:{now:NOW,offsetMs:0,timeZone:'Asia/Seoul'},products,stores:[{id:'s0',name:'독립 QA 가상 점포',address:'합성 주소',lat:37.5,lng:127,sourceOrigin:origin,coordinateSource:'fixture',coordinateAccuracy:'fixture',operatingStatus:'unverified'}],conditions:products.map(p=>({storeId:'s0',sku:p.sku,version:1,salePriceKrw:2000,purchaseCostKrw:1000,minimumOrderQty:1,orderMultiple:1,availableOrderQty:20,assortmentStatus:'listed',stockQty:0,observationStatus:'observed',observedAt:NOW,supplyStatus:'available',reason:null,orderableUntil:null,simulated:true})),requests,orders:[],policies:[{id:'policy0',storeId:'s0',enabled:false,skuScope:[],categoryScope:[],dailyBudgetKrw:100000,maxQuantityPerReview:null,version:1,approvedBy:null,approvedAt:null}],proposals:[{id:'proposal0',storeId:'s0',version:1,status:'draft',sourceFingerprint:'fixture1',constraints:{scope:'once'},lines,deferred:[],totalKrw:20000,orderId:null}],needs:[{id:'need0',actorId:'c0',storeId:'s0',originalText:'지난번에 본 새로운 간식',dialogue:[],extractedClues:['간식'],candidateSkus:[],identificationStatus:'unidentified',reason:'상품을 특정하지 못함',observedAt:NOW,sourceRefs:['synthetic_expansion'],createdAt:NOW}],notifications:[],demand:products.map(p=>({sku:p.sku,storeId:'s0',requestedQty:2,validPendingQty:2,activeLinkedQty:0,pendingOrderCoverageQty:0,unallocatedPoolQty:0,newOrderNeedQty:2,allocatedHeldQty:0,paidQty:0,deferredReasons:[],customerDetailAvailable:true})),budgets:[{storeId:'s0',budgetDay:'fixture',reservedKrw:0,securedKrw:0,usedKrw:0,limitKrw:100000}],supplyPools:[],persistence:{status:'ready',durableRevision:1}};
}
