import fs from 'node:fs';
import crypto from 'node:crypto';
import initSqlJs from 'sql.js';
const SQL=await initSqlJs();const db=new SQL.Database();
const products=JSON.parse(fs.readFileSync('data/seed/products.json','utf8'));
const stores=JSON.parse(fs.readFileSync('data/seed/stores.json','utf8'));
const config=JSON.parse(fs.readFileSync('data/seed/config.json','utf8'));
const catalogHash=crypto.createHash('sha256').update(JSON.stringify(products)).digest('hex');
db.run(fs.readFileSync('data/schema/001.sql','utf8'));
db.run('BEGIN');
for(const [key,value]of Object.entries({...config,catalogHash}))db.run('INSERT INTO schema_meta VALUES(?,?)',[key,JSON.stringify(value)]);
for(const p of products)db.run('INSERT INTO products VALUES(?,?,?,?,?,?,?,?,?)',[p.sku,p.name,p.category,p.brand,p.size,p.flavor,JSON.stringify(p.aliases),JSON.stringify(p.attributes),JSON.stringify(p.sourceOrigin)]);
for(const s of stores)db.run('INSERT INTO stores VALUES(?,?,?,?,?,?,?,?)',[s.id,s.name,s.address,s.lat,s.lng,JSON.stringify(s.sourceOrigin),s.coordinateSource,s.coordinateAccuracy]);
db.run('COMMIT');
if(db.exec('PRAGMA integrity_check')[0].values[0][0]!=='ok')throw Error('integrity');
fs.mkdirSync('public/demo',{recursive:true});const bytes=db.export();
const seedHash=crypto.createHash('sha256').update(bytes).digest('hex');
fs.writeFileSync('public/demo/seed.sqlite',bytes);fs.writeFileSync('public/demo/catalog.json',JSON.stringify(products));
fs.writeFileSync('public/demo/manifest.json',JSON.stringify({schema:config.schema,seed:config.seed,catalog:config.catalog,policy:config.policy,catalogHash,seedHash,productCount:products.length,storeCount:stores.length},null,2));
fs.copyFileSync('node_modules/sql.js/dist/sql-wasm.wasm','public/demo/sql-wasm.wasm');db.close();
console.log(JSON.stringify({productCount:products.length,storeCount:stores.length,catalogHash,seedHash}));
