import {useState} from 'react';import {createRoot} from 'react-dom/client';
import {CustomerView} from '../../src/components/customer/CustomerView';
import type {DemoClient,DemoCommand,DemoSnapshot,CommandContext} from '../../src/contracts/domain';
import {fixtureSnapshot,fixtureRequest} from './fixture';
let state=fixtureSnapshot();const commands:{command:DemoCommand;context:CommandContext}[]=[];
const control={commands,searches:0,payloads:[] as unknown[],scenario:'normal',update:null as null|((s:DemoSnapshot)=>void),reset(){state=fixtureSnapshot();this.update?.(state);},snapshot:()=>state};
Object.assign(window,{customerFixture:control});
window.fetch=async(_url,init)=>{control.searches++;const body=JSON.parse(String(init?.body));control.payloads.push(body);if(control.scenario==='error')return new Response(JSON.stringify({ok:false,error:{code:'OFFLINE',message:'모의 연결 실패',retryable:true}}),{status:503});if(control.scenario==='errorattempt')return new Response(JSON.stringify({ok:false,error:{code:'MODEL_TIMEOUT',message:'모의 모델 시간 초과',retryable:true,attempt:{providerCalled:true,model:'live-model-fixture',usage:null,latencyMs:12000,mode:'live'}}}),{status:503});if(control.scenario==='slow')await new Promise(r=>setTimeout(r,300));return new Response(JSON.stringify({ok:true,data:{...body,mode:'fixture',model:'fixture',promptVersion:'fixture',catalogVersion:'fixture',usage:{inputTokens:0,outputTokens:0,totalTokens:0,estimatedCostUsd:0},latencyMs:0,result:{action:'show_candidates',candidates:[{id:'p0',kind:'exact',sharedEvidence:['fixture 명칭'],differences:[],unknownConditions:['용량 미확인']},{id:'p1',kind:'alternative',sharedEvidence:['간식'],differences:['다른 상품·다른 맛'],unknownConditions:[]}],question:null,reason:'fixture 후보입니다.',confirmationRequired:true}}}),{status:200});};
const client:DemoClient={initialize:async()=>({ok:true,data:state}),snapshot:async()=>({ok:true,data:state}),query:async()=>({ok:true,data:[]}),switchRole:async()=>({ok:true,data:state}),subscribe:()=>()=>{},dispatch:async(command,context)=>{commands.push({command,context});state=structuredClone(state);let ids:string[]=[];if(command.type==='need.record'){const nid='need-'+commands.length;state.needs.push({id:nid,actorId:state.actor.id,...command,createdAt:state.clock.now});ids=[nid];}if(command.type==='request.create'){const r={...fixtureRequest(),id:'req-'+commands.length,sku:command.sku,storeId:command.storeId,quantity:command.quantity,acceptedPriceKrw:command.acceptedPriceKrw};state.requests.push(r);ids=[r.id];}state.session.revision++;return {ok:true,data:{commandId:context.commandId,effect:'applied',revision:state.session.revision,entityIds:ids,eventIds:[],snapshot:state}};}};
function App(){const [value,setValue]=useState(state);control.update=setValue;return <><p style={{textAlign:'center'}}>고객 UI 단독 fixture · 실제 DB/API 검증 아님</p><CustomerView snapshot={value} client={client} onSnapshot={setValue}/></>;}
createRoot(document.getElementById('root')!).render(<App/>);
