import test from 'node:test';import assert from 'node:assert/strict';
import {currentEnvelope,scopeOf,requestState,canRetryPayment,conditionText,remaining} from '../../src/components/customer/model';
import {fixtureSnapshot,fixtureRequest} from './fixture';
const snapshot=fixtureSnapshot();const e={...scopeOf(snapshot),requestId:'a',conversationId:'c',inputRevision:1,catalogHash:snapshot.versions.catalogHash};
test('response freshness binds every identity and catalog field',()=>{assert.ok(currentEnvelope(e,e,snapshot,'c',1));for(const patch of [{sessionId:'old'},{generation:0},{actorId:'other'},{roleEpoch:0},{requestId:'old'},{conversationId:'old'},{inputRevision:0},{catalogHash:'old'}])assert.equal(currentEnvelope(e,{...e,...patch},snapshot,'c',1),false);assert.equal(currentEnvelope(e,e,snapshot,'c',2),false);});
test('pending and ordered states never imply reservation',()=>{const r=fixtureRequest();assert.match(requestState(r,snapshot.clock.now).title,/확보 전/);r.links=[{orderId:'o',lineId:'l',quantity:1,active:true,releasedReason:null}];assert.match(requestState(r,snapshot.clock.now).title,/발주/);assert.match(requestState(r,snapshot.clock.now).description,/확정 전/);});
test('paid arrival wait differs from pickup; exact deadline is expired',()=>{const r=fixtureRequest();r.reservation={id:'res',code:'DEMO',status:'confirmed',quantity:1,totalKrw:2400,holdExpiresAt:null,pickupAvailableAt:null,pickupDeadlineAt:null,collectedAt:null};assert.match(requestState(r,100).description,/지금 수령할 수 없/);r.reservation.status='pickup_ready';r.reservation.pickupDeadlineAt=200;assert.match(requestState(r,199).title,/픽업 가능/);assert.match(requestState(r,200).title,/기한/);assert.equal(remaining(200,200),'기한 종료');});
test('payment retry enforces cycle, consent and hold boundary',()=>{const r=fixtureRequest();r.reservation={id:'res',code:'demo',status:'payment_failed',quantity:1,totalKrw:2400,holdExpiresAt:200,pickupAvailableAt:null,pickupDeadlineAt:null,collectedAt:null};assert.ok(canRetryPayment(r,199));assert.equal(canRetryPayment(r,200),false);r.consent.status='expired';assert.equal(canRetryPayment(r,199),false);r.consent.status='valid';r.payments=[1,2].map(attempt=>({id:String(attempt),cycle:1,attempt,status:'failed',amountKrw:2400,createdAt:100}));assert.equal(canRetryPayment(r,199),false);});
test('unknown observations and stock zero do not become discontinued',()=>{assert.match(conditionText(undefined),/미취급으로 단정할 수 없/);assert.match(conditionText({...snapshot.conditions[0],observationStatus:'error'}),/오류는 품절이 아니/);assert.match(conditionText(snapshot.conditions[0]),/재고 0개/);assert.doesNotMatch(conditionText(snapshot.conditions[0]),/공급 종료/);});
